### ISSUE TITLE
Unsupported 'format' value

### ISSUE THREAD

**Issue by bgoesswe** [getkin/kin-openapi#103]
Hey, 
I have the following setup:
Input OpenAPI snipped: 
"url": {
                                "type": "string",
                                "description": "URL to a web page with more details about the plan.",
                                "format": "url",
                                "example": "http://cool-cloud-corp.com/plans/free-plan"
                              }

I then load swagger by file and create a filter router with the following lines: 
openapi3.DefineStringFormat("url", REGEX)
swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromFile(ct.apifile)
router := openapi3filter.NewRouter().WithSwagger(swagger)

The last line causes the following error:
panic: Validating Swagger failed: Unsupported 'format' value 'url'

Even though I added it to the string formats in the first line, am I doing something wrong?
Is there a solution to this?  (the problem seems similar to #79)

**Comment by fenollp** [comment]
Here are the only `format`s supported by OAS: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types

Try with `format: uri` ;)

**Comment by m-mohr** [comment]
Still, OAS allows custom formats. So that may solve the problem for url, but not for other formats?

**Comment by fenollp** [comment]
Looks like user defined formats are supported to me: https://github.com/getkin/kin-openapi/search?q=%22uuid%22&unscoped_q=%22uuid%22

Could you provide a minified reproduction of the bug in the form of a test?

**Comment by m-mohr** [comment]
@bgoesswe Could you provide such an example?

**Comment by bgoesswe** [comment]
Nevermind, I updated to the newest version of kin-openapi and it now works fine
