### ISSUE TITLE
openapi3: can't build from latest `master`

### ISSUE THREAD

**Issue by qwerty287** [getkin/kin-openapi#1036]
Hello,

we're currently trying to update to the latest commit on `master` as we need a fix for #1016. However, after the update we can't use it anymore, the following error occurs:
```
# github.com/getkin/kin-openapi/openapi3
../../vendor/github.com/getkin/kin-openapi/openapi3/marsh.go:28:20: undefined: yaml.UnmarshalWithOrigin
cmd/server/openapi.go:24: running "go": exit status 1
```

Can we do something to fix it? Thanks!

For the related PR, see https://github.com/woodpecker-ci/woodpecker/pull/4492.

**Comment by AriehSchneier** [comment]
[oasdiff/yaml3](https://github.com/oasdiff/yaml) is just a fork of [invopop/yaml](https://github.com/invopop/yaml), we shouldn't be using the changes until they are merged in to the main project ([read both answers here](https://stackoverflow.com/questions/68007393/avoid-writing-replace-for-recursive-dependency-for-local-modules)).
