### ISSUE TITLE
Read schema with refs

### ISSUE THREAD

**Issue by AlexAslan** [getkin/kin-openapi#105]
Hello...Is it possible somehow to get a schema with refs in on go? Currently using something like this `swagger.Components.Schemas["ResponseTest"]` returns `{"data":{"items":{"$ref":"#/components/schemas/TestItem"},"meta":{"$ref":"#/components/schemas/ResponseMeta"},"type":"array"},"description":""}`. Ideally I would like to get the full schema instead of the ref

**Comment by fenollp** [comment]
`SchemaRef` has a `Value` field.
