### ISSUE TITLE
Add DefineNumberFormat function

### ISSUE THREAD

**Issue by bgoesswe** [getkin/kin-openapi#107]
Hey, 
We use a custom format with type "number" e.g.:
"eo:epsg": {
    "type": "number",
    "format": "epsg-code",
    ...
 }

There is the function DefineStringFormat implemented into openapi3 (related issues #103, #79), but it only handles elements with type "string". So there is a need for a DefineNumberFormat function.

**Comment by fenollp** [comment]
Pars welcomed!
