### ISSUE TITLE
Deviation from official Open API 3.0 Documentation

### ISSUE THREAD

**Issue by alangordon** [getkin/kin-openapi#111]
Hi,

What is the reasoning or explanation behind the difference here

https://godoc.org/github.com/getkin/kin-openapi/openapi3#Swagger

vs

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#openapi-object

The inconsistency/deviation I am referring to is that in the official docs `path` is required but in the implementation in this library it is not required.

There are other inconsistencies but this one is the main one - other examples include:
 - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#infoObject (different required fields)

**Comment by fenollp** [comment]
The vaguely stated goal of this project is to fully comply with the OpenAPIv3 spec as much as can be.
I believe you have found bugs & would love to review your PRs ;)

**Comment by fenollp** [comment]
Looks like https://github.com/getkin/kin-openapi/pull/114 addressed your concerns
