### ISSUE TITLE
Leading slash in path is not mandatory

### ISSUE THREAD

**Issue by tuzkov** [getkin/kin-openapi#112]
By [OpenAPI 3.0.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#pathsObject) Paths Object path have description - "The field name MUST begin with a slash".

But kin-openapi/openapi3 can handle such docs:
---
            openapi: "3.0"
            info:
              version: "1.0"
              title: sample
            basePath: /adc/v1
            paths:
              foo/bar:
                get:
                  responses:
                    200:
                      description: description
              /foo/{var}/:
                get:
                  responses:
                    200:
                      description: description

This spec parses fine and return path 'foo/bar' but doesn't

**Comment by fenollp** [comment]
Thanks for finding this, verifying with the spec & reporting!

The fix should be simple enough: calling https://golang.org/pkg/path/filepath/#IsAbs. I'll look into it when time permits, or you can race me to it ;)

**Comment by fenollp** [comment]
I believe this was fixed even before the issue was opened but there was no tag to upgrade to.

Anyway a regression test is added in https://github.com/getkin/kin-openapi/pull/209
