### ISSUE TITLE
Swagger v2 to v3 conversion

### ISSUE THREAD

**Issue by eclipse1985** [getkin/kin-openapi#113]
In the README is stated that `openapi2` package supports 

`OpenAPI 2 files, including serialization, deserialization, and validation` 

But I can't find a way to read a swagger v2 file.

I need to convert a swagger v2 file to swagger v3. Is that possible in any way with `kin-openapi` ?

**Comment by dinusha92** [comment]
I have a similar requirement. @eclipse1985 were you able to achieve this? :)

**Comment by eclipse1985** [comment]
Unfortunately no

**Comment by tschaub** [comment]
@eclipse1985 @dinusha92 - assuming you have read your v2 spec as `[]byte`, you can use a function like this to convert to v3:
```go
func V2ToV3(v2Data []byte) ([]byte, error) {
	v2Spec := &openapi2.Swagger{}
	if err := json.Unmarshal(v2Data, v2Spec); err != nil {
		return nil, err
	}

	v3Spec, err := openapi2conv.ToV3Swagger(v2Spec)
	if err != nil {
		return nil, err
	}

	return json.Marshal(v3Spec)
}
```

**Comment by eclipse1985** [comment]
Yes, I just tried, and you are right. We can close this issue.

**Comment by OneCricketeer** [comment]
Could this be a CLI command?
