### ISSUE TITLE
Response Validation Does Not Validate Response Property types

### ISSUE THREAD

**Issue by tateexon** [getkin/kin-openapi#123]
I was using this library to do some request and response validation and noticed that when I pass in a string to a respnse property when it should be a number or integer the validation still passes.
Here is my example openapi that has a 200 response returning a variable "badguy" that should be an integer:
```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "Verify stuff fails",
    "version": "1.0.0"
  },
  "paths": {
    "/badguy": {
      "get": {
        "summary": "Get the bad guy",
        "description": "get the bad guy",
        "responses": {
          "200": {
            "description": "blarg",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "badguy": {
                      "type": "integer",
                      "description": "using this to force a failure to test validation works",
                      "example": 123
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

And then using the example from this projects readme:
```go
func TestUnitNumberShouldFailIfStringIsReturned(t *testing.T) {
	router := openapi3filter.NewRouter().WithSwaggerFromFile("../min.json")
	ctx := context.TODO()
	httpReq, _ := http.NewRequest(http.MethodGet, "/badguy", nil)

	// Find route
	route, pathParams, _ := router.FindRoute(httpReq.Method, httpReq.URL)

	// Validate request
	requestValidationInput := &openapi3filter.RequestValidationInput{
		Request:    httpReq,
		PathParams: pathParams,
		Route:      route,
	}
	if err := openapi3filter.ValidateRequest(ctx, requestValidationInput); err != nil {
		panic(err)
	}

	var (
		respStatus      = 200
		respContentType = "application/json"
		respBody        = bytes.NewBufferString(`{"badguy":"blarg"}`)
	)

	log.Println("Response:", respStatus)
	responseValidationInput := &openapi3filter.ResponseValidationInput{
		RequestValidationInput: requestValidationInput,
		Status:                 respStatus,
		Header: http.Header{
			"Content-Type": []string{
				respContentType,
			},
		},
	}
	if respBody != nil {
		data, _ := json.Marshal(respBody)
		responseValidationInput.SetBodyBytes(data)
	}

	// Validate response.
	if err := openapi3filter.ValidateResponse(ctx, responseValidationInput); err != nil {
		panic(err)
	}
}
```
I return {"badguy":"blarg"} as the response body to validate. When running the validation, it passes. I expected it to fail. Is this an incorrect expectation for this library?

Edit: Added a branch with the test added to it to make debugging easier: https://github.com/tateexon/kin-openapi/tree/verify_response_parameter_type_test

**Comment by tateexon** [comment]
After a little debugging it looks like setting the respBody with this:
```
respBody        = bytes.NewBufferString(`{"badguy":"blarg"}`)
```
And then doing a json.Marshal with that:
```
data, _ := json.Marshal(respBody)
```
produces a data variable with "{}" and this is why it fails. 
If I change the json.Marshal to be this:
```
data, _ := json.Marshal(map[string]string{"badguy": "blarg"})
```
then it passes. So I just need to figure out how to get my response body string to json.Marshal correctly. If and when I figure out how to do this properly I will update the readme example so others don't run into this same issue.

**Comment by tateexon** [comment]
Also to note is that the error response for this feels backwards. In the example I posted above when it actually marshals the data correctly then the error that gets thrown by the ValidateResponse function is:
```
    validation_test.go:788: err is: response body doesn't match the schema: Error at "/badguy":Field must be set to string or not be present
        Schema:
          {
            "description": "using this to force a failure to test validation works",
            "example": 123,
            "type": "integer"
          }
        
        Value:
          "integer"
FAIL
```
It says "Field must be set to string or not be present" which is backwards. The openapi schema says it should be an integer so the message should read "Field must be set to an integer or not be present".

**Comment by tateexon** [comment]
Turns out all I needed to change was the setting of the responseValidationInput.SetBodyBytes to this and not even worry about the whole json.Marshal stuff:
```go
responseValidationInput.SetBodyBytes([]byte(`{"badguy":"blarg"}`))
```
Closing the issue.

**Comment by a89bb05a** [comment]
> Turns out all I needed to change was the setting of the responseValidationInput.SetBodyBytes to this and not even worry about the whole json.Marshal stuff:

oh my god, thanks guys!!!
