### ISSUE TITLE
Link type has no OperationRef field

### ISSUE THREAD

**Issue by dunglas** [getkin/kin-openapi#130]
According to the specification, `Link` should have an `OperationRef` field. It's not a blocker, because currently this data is available in the `ExtensionProps` field.

**Comment by fenollp** [comment]
Indeed links impl seems incorrect on first look
* https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#link-object
* https://github.com/getkin/kin-openapi/blob/41b6ab94624e5f2336cf559b0482183c5b1c5067/openapi3/link.go

PRs welcomed ;)

**Comment by matej-g** [comment]
Hello,
I would like to contribute on this, but I'm trying to understand the task fully - does this entail just updating the struct declaration in `link.go` to include `OperationRef`?

**Comment by dunglas** [comment]
It would be even nicer to be able to also retrieve the related operation struct.

**Comment by matej-g** [comment]
Would this be a method(s) defined on the `Swagger` struct? Should it be possible to retrieve the operation struct by both ID and Ref? Trying to confirm once again I understand correctly.

**Comment by fenollp** [comment]
@dunglas Fixed by https://github.com/getkin/kin-openapi/pull/189
