### ISSUE TITLE
validation of default value conformity

### ISSUE THREAD

**Issue by bonnyr** [getkin/kin-openapi#136]
The OpenAPI Spec states that the default property, when applied to a schema must use the same values as the underlying property type, thus, a string property cannot have an integer value specified etc.

> https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schema-object
> default - The default value represents what would be assumed by the consumer of the input as the value of the schema if one is not provided. Unlike JSON Schema, the value MUST conform to the defined type for the Schema Object defined at the same level. For example, if type is string, then default can be "foo" but cannot be 1.

This is currently not covered by the project as best I can tell.

Is this on anyone's radar to fix? I'm currently working on a private version that tackles that for our use case, but will be happy to upstream this if needed

**Comment by fenollp** [comment]
No idea if it's on anyone's radar. This project is about implementing the whole OA3 spec so I'd gladly review your PRs :)
