### ISSUE TITLE
DataType Validation

### ISSUE THREAD

**Issue by FrancisLennon17** [getkin/kin-openapi#146]
Using the openapi3 library to validate a definition example found under the OpenAPI-Specification GitHub found [here](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/uber.json).

(Im using this library to convert from swagger 2 to openapi 3, then validating it)

This library returns an `unsupportedFormat` error for the below parameter as uuid is not a supported format for the string type.

![image](https://user-images.githubusercontent.com/28549164/69651305-c9b54f00-1067-11ea-81de-78ea37a5bcfa.png)

[Here](https://github.com/getkin/kin-openapi/blob/1116f3ecaa880095aa0e8f4eb64a6dc04c8a288e/openapi3/schema.go#L488-L525) is where the error is being thrown. A comment says that those specified are the formats listed there are the formats supported by OpenAPIv3, but after reading through the OpenAPI-Specification [docs](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#format) it says:
> Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification

I have a number of undefined formats in some openapi3 and swagger2 definitions I'm working with, and the validate function will not pass due to this. Could this part of the validate function be removed as it seems these formats can be used?

**Comment by Arms-Li** [comment]
you can register your own format and pattern by call

```go
openapi3.DefineStringFormat(name string, pattern string)
```

**Comment by benfdking** [comment]
We are encountering the same issue. Whereas the validator against an enitity works:

```go
case "string":
		if format := schema.Format; len(format) > 0 {
			switch format {
			// Supported by OpenAPIv3.0.1:
			case "byte", "binary", "date", "date-time", "password":
				// In JSON Draft-07 (not validated yet though):
			case "regex":
			case "time", "email", "idn-email":
			case "hostname", "idn-hostname", "ipv4", "ipv6":
			case "uri", "uri-reference", "iri", "iri-reference", "uri-template":
			case "json-pointer", "relative-json-pointer":
			default:
				return unsupportedFormat(format)
			}
		}
```

The validation of the schema itself does not:

```go 
case "string":
		if format := schema.Format; len(format) > 0 {
			switch format {
			// Supported by OpenAPIv3.0.1:
			case "byte", "binary", "date", "date-time", "password":
				// In JSON Draft-07 (not validated yet though):
			case "regex":
			case "time", "email", "idn-email":
			case "hostname", "idn-hostname", "ipv4", "ipv6":
			case "uri", "uri-reference", "iri", "iri-reference", "uri-template":
			case "json-pointer", "relative-json-pointer":
			default:
				// Try to check for custom defined formats
				if _, ok := SchemaStringFormats[format]; !ok {
					return unsupportedFormat(format)
				}
			}
		}
```

**Comment by fenollp** [comment]
@benfdking did you try @emnnqqs's suggestion?

**Comment by benfdking** [comment]
I have but when setting up the openapifilter, the function validates the schema itself as shown below:

```
func (router *Router) AddSwagger(swagger *openapi3.Swagger) error {
	if err := swagger.Validate(context.TODO()); err != nil {
		return fmt.Errorf("Validating Swagger failed: %v", err)
	}
        ...
}
```

That validation does not use `SchemaStringFormats` and so it fails.

**Comment by fenollp** [comment]
What makes you say SchemaStringFormats is not used?
Where did you get that first code snippet in https://github.com/getkin/kin-openapi/issues/146#issuecomment-597766554?
Can you share your code + spec in full please?

**Comment by benfdking** [comment]
@fenollp https://github.com/getkin/kin-openapi/blob/e7e26782ae6a4633291fe444c684d43cb8dd9a14/openapi3/schema.go#L513

**Comment by fenollp** [comment]
Yeah no this file does not contain this snippet:
```go
case "string":
		if format := schema.Format; len(format) > 0 {
			switch format {
			// Supported by OpenAPIv3.0.1:
			case "byte", "binary", "date", "date-time", "password":
				// In JSON Draft-07 (not validated yet though):
			case "regex":
			case "time", "email", "idn-email":
			case "hostname", "idn-hostname", "ipv4", "ipv6":
			case "uri", "uri-reference", "iri", "iri-reference", "uri-template":
			case "json-pointer", "relative-json-pointer":
			default:
				return unsupportedFormat(format)
			}
		}
```
Please answer my other questions.

**Comment by paulmil1** [comment]
i confirm this,  using
`openapi3.DefineStringFormat("uuid", `^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`)
`
does not work as the array is never accessed, problem is that the switch here
https://github.com/getkin/kin-openapi/issues/146#issuecomment-597766554
ignores custom types, and so the switch always fails with: Validating Swagger failed: Unsupported 'format' value 'uuid'

**Comment by paulmil1** [comment]
can u just push @benfdking  's fix proposal through? it would fix it, so far, we cannot use custom types

**Comment by benfdking** [comment]
I think @fenollp, this is in fact a downstream version problem. The codegen library that I am using is pinned to. Is there any reason why versioned releases haven't been pushed forward? I will be trying to push the codegen library to use a later version of kin-openapi. 

```
	github.com/getkin/kin-openapi v0.2.0
``

**Comment by paulmil1** [comment]
oh yeah, its actually pushed, what we need is a new release

**Comment by fenollp** [comment]
Ah this makes sense. I just cut https://github.com/getkin/kin-openapi/releases/tag/v0.3.0 to help you.
Note: you can use https://golang.org/cmd/go/#hdr-Edit_go_mod_from_tools_or_scripts with `-replace=old[@v]=new[@v]` in the future to troubleshoot this packaging problem.

There isn't a plan on when to cut releases but given how go modules work I'll try to cut a minor release per PR merged in the future. I need to look for a github action to do this for me.

Feel free to close this issue if this solves it :)

**Comment by benfdking** [comment]
From my point of view, my issue isn't done ... ^ got to wait on that bad boy (bad have used our fork to get it up and running in the meantime). But I do think this issue is done for this repo. Thank you very much both @fenollp and @paulmil1.

**Comment by FrancisLennon17** [comment]
@emnnqqs @fenollp 
My team work with a lot of client's openapi definitions, and we don't know all the possible formats that they could have. Looping through to register each and every place in the definition a format property could be found is impractical and slow. Is this check really necessary?

**Comment by fenollp** [comment]
@FrancisLennon17 I'm open to a (probably package wide `var`) setting that disables checking `format` but I'd have to be off by default.
