### ISSUE TITLE
Validator: Path item query parameters are not validated when operation parametes are not defined

### ISSUE THREAD

**Issue by pali** [getkin/kin-openapi#151]
Test case:
```json
{
	"openapi": "3.0.0",
	"info": {
		"title": "title",
		"version": "0.0.1"
	},
	"paths": {
		"/path": {
			"get": {
				"responses": {
					"200": {}
				}
			},
			"parameters": [
				{
					"name": "par1",
					"in": "query",
					"required": true,
					"schema": {
						"type": "integer"
					}
				}
			]
		}
	}
}
```

When `openapi3filter.ValidateRequest` is called for `GET` method on URI `/path?par2=bla` with above schema, validation success even that `par1` was not specified in URI and was set as `required`. But validation in this case should fail when required parameter is not specified.

When I modified above schema to include empty list of operation query parameters for GET method, then validation of `par1` parameter started working.

```json
			"get": {
				"parameters": [],
                                 ...
			},
```

So `openapi3filter.ValidateRequest` does not validate query parameters correctly when operation parameters are not specified (at least as empty list).

Problem is in this part of code:
https://github.com/getkin/kin-openapi/blob/4878ab9a8727b6874710f243f8773978d2cdd151/openapi3filter/validate_request.go#L41-L52
`ValidateParameter` is not called when `operationParameters` is nil which is incorrect. `ValidateParameter` needs to be always called.

Below is a simple patch which fixes this problem:
```diff
diff --git a/openapi3filter/validate_request.go b/openapi3filter/validate_request.go
index 62d314a..dcd9d38 100644
--- a/openapi3filter/validate_request.go
+++ b/openapi3filter/validate_request.go
@@ -45,9 +45,9 @@ func ValidateRequest(c context.Context, input *RequestValidationInput) error {
 			if override := operationParameters.GetByInAndName(parameter.In, parameter.Name); override != nil {
 				continue
 			}
-			if err := ValidateParameter(c, input, parameter); err != nil {
-				return err
-			}
+		}
+		if err := ValidateParameter(c, input, parameter); err != nil {
+			return err
 		}
 	}
 

```

**Comment by fenollp** [comment]
Awesome work! Thanks!
