### ISSUE TITLE
Receiving incorrect error, when endpoint is path with unsupported method

### ISSUE THREAD

**Issue by ErrorBoi** [getkin/kin-openapi#158]
Hi, I've found that when I send request to a path with unsupported method, error message in response is "Path was not found" instead of ["Path doesn't support the HTTP method"](https://github.com/getkin/kin-openapi/blob/master/openapi3filter/router.go#L199)

Steps to reproduce:
1. Run a server, generated from OpenAPI specification. For example, [Petstore](https://github.com/deepmap/oapi-codegen/blob/master/examples/petstore-expanded/chi/petstore.go#L16) from OpenAPI examples
2. Send request to a path with unsupported method, for example PUT /users

Actual result: 
```
{
    "message": "Path was not found"
}
```
Expected result:
```
{
    "message": "Path doesn't support the HTTP method"
}
```

**Comment by fenollp** [comment]
`pathpattern` takes the method and the path pattern as one whole argument for some reason that I've yet to uncover, and that is the reason why it can't differentiate between "path not found" and "path doesnt support method".

I have started reworking this but feel free to chime in if you feel like it.

**Comment by ErrorBoi** [comment]
Method and path pattern are concatenated [here](https://github.com/getkin/kin-openapi/blob/master/openapi3filter/router.go#L176), maybe it's the reason.

Maybe "Path doesn't support the HTTP method" error should be thrown, if node doesn't match any suffix, but path pattern is listed in swagger spec?

**Comment by ErrorBoi** [comment]
I made a simple fix, please take a look if it's ok @fenollp 
https://github.com/getkin/kin-openapi/compare/master...ErrorBoi:master

**Comment by ErrorBoi** [comment]
After current fix "Path was not found" error is never thrown. "Path doesn't support the HTTP method" error is always thrown instead.
I created Pull Request with fix (tested it on 2 server instances and it works correctly)
https://github.com/getkin/kin-openapi/pull/161
