### ISSUE TITLE
Incorrect validation of array

### ISSUE THREAD

**Issue by pali** [getkin/kin-openapi#181]
Here is simple OAS3 schema which should accept array of any number of elements and of any types:
```json
{
    "openapi": "3.0.0",
    "info": {
        "version": "1.0.0",
        "title": "test"
    },
    "paths": {
        "/": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ANY_ARRAY"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components" : {
        "schemas" : {
            "ANY_ARRAY" : {
                "type": "array",
                "items": {}
            }
        }
    }
}
```
But kin-openapi validator not accept `[ null ]` or `[ null, null ]` or `[ null, null, null ]` for above schema and fails on error:
```
response body doesn't match the schema: Error at "/0":Value is not nullable
```

**Comment by fenollp** [comment]
This is working as intended. Note: OpenAPI JSON schemas are not exactly JSON Schema Draft 4.
See https://swagger.io/docs/specification/data-models/data-types/
> If the null value needs to be allowed, add nullable: true:
```
components:
  schemas:
    AnyValue:
      nullable: true
      description: Can be any value, including `null`.
```

**Comment by pali** [comment]
Hi @fenollp! Thank you for a link.

I have looked only *official* OpenAPI 3.0.3 specification for nullable type https://swagger.io/specification/#schemaNullable which says:
> A `true` value adds `"null"` to the allowed type specified by the `type` keyword, only if `type` is explicitly defined within the same Schema Object. Other Schema Object constraints retain their defined behavior, and therefore may disallow the use of `null` as a value. A `false` value leaves the specified or default type unmodified. The default value is `false`.

So according to OpenAPI 3.0.3 specification, you cannot use `nullable` without specifying `type` and therefore following schema (which you suggested) is *invalid*:
```yaml
components:
  schemas:
    AnyValue:
      nullable: true
      description: Can be any value, including `null`.
```

So it looks like that OpenAPI itself is inconsistent... if it says that above should be used, even it is invalid according to specification.
