### ISSUE TITLE
Schema propety 'n' interpreted as 'false'

### ISSUE THREAD

**Issue by glooms** [getkin/kin-openapi#182]
I found an interesting bug. It seems that if a I have an openapi3 specification with a Schema in it containing a property `n` it gets interpreted as `false`. But only if the file format is `.yaml` and not `.json`.

Also seems to be the case for `N`, `No` and `no` but not `noo`. Also, the type didn't seem to matter. So... it's a puzzler!
Anyway, if you want to reproduce you can use this API-spec (generated with [https://editor.swagger.io](https://editor.swagger.io/)) and the code snippet.
The version I produced this with, according to my `go.mod`, was: `github.com/getkin/kin-openapi v0.2.1-0.20191128230727-4878ab9a8727`.
```yaml
openapi: 3.0.0
info:
  version: 0.0.0
  title: TestAPI
  description: Test API used as testdata
paths: {}
components:
  schemas:
    A:
      type: object
      properties:
        n:
          type: boolean
```

```go
package test

import (
        "testing"

        "github.com/getkin/kin-openapi/openapi3"
)

func TestOpenAPI(t *testing.T) {
        spec, err := openapi3.NewSwaggerLoader().LoadSwaggerFromFile("./openapi.yaml")
        if err != nil {
                t.Error("Failed to parse test-file:", err)
        }
        schema := spec.Components.Schemas["A"].Value
        for k := range schema.Properties {
                t.Log(k)
        }
        if _, ok := schema.Properties["n"]; !ok {
                t.Error("Property 'n' did not exist")
        }
        if _, ok := schema.Properties["false"]; ok {
                t.Error("Property 'false' did exist")
        }
}

```

**Comment by fenollp** [comment]
YAML can be surprising: https://yaml.org/type/bool.html

**Comment by glooms** [comment]
Hah! Fair enough, thanks for the answer!
Nice library btw, keep up the good work :)
