### ISSUE TITLE
omitempty in structs producing invalid definitions

### ISSUE THREAD

**Issue by FrancisLennon17** [getkin/kin-openapi#185]
There are omitempty tags that end up removing a required field when sending the struct. The `description` field is required as per the Open API 3 specification, and therefore is not a valid definition. 

Could either 
- The omit empty tags be removed from any fields required by the Open API 3 specification
- Or validation added not to allow any required fields, like description, to have an empty string (similar to what has been done for info.Title/info.Version)

This behaviour worked as expected in previous versions up until [this](https://github.com/getkin/kin-openapi/pull/148/files#diff-4da5065edd98a754c28386877c1f2598R28) change was made

```
info:
  title: 'asdf'
  version: '1'
openapi: 3.0.0
paths:
  /test:
    post:
      responses:
        '200':
          description: ''
  /test2:
    post:
      parameters: 
        - name: ''
          in: 'query'
          schema: {}
          required: false
        - name: '1'
          in: 'query'
          content: 
            application/json: {}
          required: false
        - name: '2'
          in: 'query'
          content: 
            application/json: 
              schema: {}
          required: false
      requestBody:
        content: {}
      responses:
        '200':
          description: ''
```

**Comment by fenollp** [comment]
It is unclear whether `description: ''` is to be considered different than not mentioning the field at all IMO.
While I am sorry some of your specs were broken by me merging #148 I believe that second option (forbidding empty required fields) should be the way to go.

**Comment by FrancisLennon17** [comment]
A blank string is valid against the Open API specification from what I've seen in various online validation tools. Enforcing non-empty strings for fields seems counterproductive. Its impractical for developers to ensure that each and every response/parameter/reference description string is not empty in a definition. And I can't imagine that it is common for each and every one to be filled in.

**Comment by fenollp** [comment]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#response-object
> REQUIRED. A short description of the response. CommonMark syntax MAY be used for rich text representation.

IMO various validation tools are disregarding the part about `A short description of the response.` for convenience when a spec is produced by a human. This lib however strives to implement the spec.

**Comment by bryanbecker** [comment]
My two cents (some team as Francis):

We've looked at a huge number of OpenAPI docs, and something closing in on 100% of them have at least on operation with a missing description.  This could be attributed to the fact that generally API docs are forever a work-in-progress.

While technically required by the spec, if the implementation works on less than 50% of the target use cases, I would argue the library should allow it.  (Also, you could argue an empty string is still a string).

**Comment by fenollp** [comment]
That is true. I guess the first solution is the least troublesome for users?

**Comment by bryanbecker** [comment]
I would say so.  Another reason why it's less troublesome is because the producer of the OpenAPI document (ex. Team A), and the consumer (Team B) are often totally different teams (and maybe different organizations or companies).

Meaning if the doc is missing some information, Team B has no ability on their own to remediate the situation.  So all they would do here is either: a) forget it and move on, b) add gibberish placeholder text
