### ISSUE TITLE
`linkRef.Value.Headers` has type `Schema`

### ISSUE THREAD

**Issue by pseudo-su** [getkin/kin-openapi#188]
I have recently written some code that walks the `openapi3.Swagger` object, traversing all objects that can contain nested refs.

I have noticed that for some reason linkRef.Value.Headers is a `map[string]*Schema` instead of a `map[string]*SchemaRef` or `map[string]*HeaderRef`.

I think this is a bug.

The original PR where I ran into this: https://github.com/deepmap/oapi-codegen/pull/154

**Comment by pseudo-su** [comment]
Actually after investigating this a little bit I'm even more confused, I can't find any reference to `links` having `headers` in the OpenAPI spec https://swagger.io/specification/#linkObject

**Comment by fenollp** [comment]
Indeed this struct seems way out of spec https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#linkObject
Missing fields:
* operationRef
* requestBody
* server
Out-of-spec fields:
* href
* headers

If you can turn your PR around in order add the missing fields & remove the out of spec ones that'd be great :)

**Comment by pseudo-su** [comment]
awesome, I'll have a look tomorrow
