### ISSUE TITLE
Question: possibility to add custom validations

### ISSUE THREAD

**Issue by peter-plochan** [getkin/kin-openapi#191]
This is follow-up to #190. 
In my OpenAPI 3 definition, I would like to introduce `x-patternProperties` vendor extension based on [JSON-schema pattern properties](https://json-schema.org/understanding-json-schema/reference/object.html#pattern-properties). So let's assume that I have a schema with this extension containing a map of patterns with schemas.
Is there a possibility to add custom validation of such extension to the validator?

**Comment by fenollp** [comment]
While you should be able to decode and use the extension after/before native schema validation, I would suggest you aim for OpenAPIv3.1 support (if you can) as it sports standard JSON Schema schemas.
See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#schemaObject
cc #230
