### ISSUE TITLE
help with using library

### ISSUE THREAD

**Issue by SrikumarChari** [getkin/kin-openapi#199]
Awesome library. Am using to convert Google Api spec to openapi 3, which requires me to parse Google format and "hand" build the OpenAPI equivalents. I followed some of the samples, went through the code (perhaps maybe not enough :( )...

when I create parameters (and this applies even to Schema/SchemaRef), I create a Parameter struct and then a ParameterRef and add it to the operation. However, when I spit out the yaml file, I get something like this:

parameters:
    $.xgafv:
      ref: $.xgafv
      value:
        extensionprops: {}
        name: $.xgafv
        in: query
        description: V1 error format.
        required: true
        schema:
          ref: ""
          value:
            extensionprops: {}
            type: string
        example:
        - "1"
        - "2"

Am I missing a step or is OpenAPI 3.x output not supported?

Thanks in advance.
Sri

**Comment by fenollp** [comment]
What's the issue?

**Comment by SrikumarChari** [comment]
The output structure doesn't seem right. Is there a flag or something I need to do? At first I thought I was using the library incorrectly but even if I load an OpenAPI file through the library and write the yaml on successfully parsing the file, the output can't be re-read back as an OpenAPI file.

**Comment by fenollp** [comment]
Could you write a minimal Go script/test reproducing your issue?

**Comment by fenollp** [comment]
Please reopen with minimal code showing the issue.
