### ISSUE TITLE
Handling "default" in request body schema

### ISSUE THREAD

**Issue by cdent** [getkin/kin-openapi#206]
(Apologies if I'm getting the nature of "default" completely wrong, but...)

I have an openapi3 request body schema which includes:

```json
          "group_by_time": {
            "default": true,
            "description": "Aggregate data over the provided time range, using the provided resolution. Default: true",
            "type": "boolean"
          },
```

For me, the ideal result of RequestBodyValidation would be a changed body that has `"group_by_time": true` if it is not otherwise set. I can think of many of reasons why this is a bad idea: req.Body -> JSON -> to new JSON -> to new Body is icky.

Also it doesn't appear that the json visitor would make the changes, as currently written.

So what is the correct or preferred way of achieving this? Should I simply be checking/setting the default in my code.

If there is a way to make this possible in the kin-openapi, I'm happy to work on the code if someone pushes me in the right direction.

**Comment by fenollp** [comment]
Agreed that the default (if provided in schema) should be set in the request payload if missing.
The same should probably be done for the response payload.

> default - The default value represents what would be assumed by the consumer of the input as the value of the schema if one is not provided. Unlike JSON Schema, the value MUST conform to the defined type for the Schema Object defined at the same level. For example, if type is string, then default can be "foo" but cannot be 1.

Did you take a look around https://github.com/getkin/kin-openapi/tree/master/openapi3filter?

Note: [`default`'s type is not enforced yet](https://github.com/getkin/kin-openapi/issues/136)

**Comment by cdent** [comment]
Thanks for the quick response. I haven't dug deeply yet, but I did browse around that package to get a sense of the flow of things. I'll see if I can make any progress. Unfortunately I can't promise to be fast about this, but I'll attempt to give it some attention.

**Comment by fenollp** [comment]
This is probably close to what you want: https://github.com/getkin/kin-openapi/pull/162/files#diff-84d2e20da533e3df9ee04610d43b046fR115

**Comment by cdent** [comment]
Yes, it does look like half of #162 is what I'm after.

As is perhaps obvious by now, I had zero time to work on this in 2020 and 2021 isn't looking any better. If there's anything I can do to help move #162 along, let me know.

**Comment by fenollp** [comment]
I started something at https://github.com/getkin/kin-openapi/pull/285. Take a look & commit when you find time :)

**Comment by Raymond26** [comment]
Hey @fenollp - know what we need to get your https://github.com/getkin/kin-openapi/pull/285 change moving along?

**Comment by fenollp** [comment]
Hi @Raymond26 thanks for taking interest in this.
I have patched up a quick demo, iterating on the mentioned PR.
You are more than welcome to continue / complete this. I believe I dusted up the tricky parts and the rest should follow the `decoders` dual.

**Comment by nic-6443** [comment]
@fenollp Hi, thank you for such a great project, this feature about default value is very nice, I finished the `query`/`header`/`cookie` part based on your #285 and added complete tests, this is the new #544 (or should I merge it to your existing branch?) Do you have time to review it? Thank you very much!
