### ISSUE TITLE
Add examples on how to parse/work with openapi 3 definitions

### ISSUE THREAD

**Issue by goapifirst** [getkin/kin-openapi#216]
I am not completely clear from the README if this library is able to parse an OpenAPI 3 definition... and if it is, does it work with multi file definitions where refs are to external files? If not, how are refs to external files handled?

If it does parse the definition, how do we use it to say, iterate the paths, components, find vendor extensions, tags, etc?

I would like to try to play with it a bit, but hard to tell if it actually supports parsing the definition into a usable object that I can then use to navigate the structure in code. Please set up some examples that show things like loading a single (or multi) file, accessing/iterating paths/urls/resources, getting specific payloads of specific resources, iterating all components/definitions, getting vendor extensions or being able to check for them or tags at any point where they are allowed, etc.

Thank you.

**Comment by fenollp** [comment]
I see tests as some form of examples.
Did you take a look at https://github.com/getkin/kin-openapi/blob/3fd16049f0f4d3ac3aed49ec8999675ba2f3163b/openapi3/swagger_loader_test.go ?
In particular https://github.com/getkin/kin-openapi/blob/3fd16049f0f4d3ac3aed49ec8999675ba2f3163b/openapi3/swagger_loader_test.go#L167-L199

See also https://pkg.go.dev/github.com/getkin/kin-openapi@v0.9.0/openapi3?tab=doc

If you find what you need could you make a PR adding the example you'd have liked to find in the README?

Thanks and have a nice day

**Comment by fenollp** [comment]
Feel free to reopen if you need more info

**Comment by stefanclerk** [comment]
@fenollp do you have any examples for loading multiple files into a router?

it is clear for a single file you can simply do `.NewRouter().WithSwaggerFromFile("blah.yml")` but it is unclear how to resolve external references when taking this route.

Once I figure out how to do it I will be happy to provide a PR to update the README with an example. I've looked through all of the tests and cannot find a great example for building a router from multiple openapi files.

thanks!

**Comment by stefanclerk** [comment]
I was able to get something working, i'll add it here for anyone else confused:

`WithSwaggerFromFile` does not support multiple files, you will get an error "Encountered non-allowed external reference"

so in order to get a Router with multiple openapi files you have to do the following:

```
swaggerLoader := &openapi3.SwaggerLoader{
	IsExternalRefsAllowed: true,
}
swagger, _ := swaggerLoader.LoadSwaggerFromFile("pathto/file.yml")
swaggerRouter := openapi3filter.NewRouter().WithSwagger(swagger)

```
