### ISSUE TITLE
References to Relative Documents With Embedded Schema cannot be resolved on Windows

### ISSUE THREAD

**Issue by F7502** [getkin/kin-openapi#220]
I want to parse an OpenAPI file that references another OpenAPI file like this (example taken from https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#referenceObject):

```json
{
  "$ref": "definitions.json#/Pet"
}
```

I do this as follows:

```go
func main() {
	// on Linux e.g. /dev/my-openapi.json
	// on Windows e.g. C:/dev/my-openapi.json
	openapi := filepath.FromSlash("C:/dev/my-openapi.json")
	swg := openapi3.NewSwaggerLoader()
	swg.IsExternalRefsAllowed = true
	oas, err := swg.LoadSwaggerFromFile(openapi)
	if err != nil {
		fmt.Println(err.Error())
	} else {
		fmt.Printf("%s\n", oas.Info.Title)
	}
}
```

This works on Linux (tested on a Mac) but not on Windows. Here I get something like this (`my-openapi.json` references `my-other-openapi.json` and both files are located in the same folder):

```
Error while resolving reference 'my-other-openapi.json#/components/responses/DefaultResponse': open my-other-openapi.json: The system cannot find the file specified.
```

**Comment by fenollp** [comment]
What does C:/dev/my-openapi.json contain?

**Comment by F7502** [comment]
> What does C:/dev/my-openapi.json contain?

Please find the files attached and thanks for having a look :-)
[testdata.zip](https://github.com/getkin/kin-openapi/files/4751888/testdata.zip)

**Comment by fenollp** [comment]
Hey I was attempting a reproduction over at https://github.com/getkin/kin-openapi/compare/master...fenollp:issue220 until I realized I do not have a Windows machine around.

I'm a bit busy right now but I'll setup windows CI before going back to it.

In the meantime if you can dig into it yourself that'll help a lot.
From here it looks like some code places need to be wrapped in `filepath.FromSlash`.
