### ISSUE TITLE
LoadSwaggerFromURIFunc is not called for eternal reference loading via `loadSingleElementFromURI()`

### ISSUE THREAD

**Issue by ghost** [getkin/kin-openapi#231]
I'm attempting to use the LoadSwaggerFromURIFunc() to allow us to stub out the URI access and I've found that when references are required for a single element (apparently when there is no # in the path) the helper func is not called and the URI is accessed directly.

**Comment by fenollp** [comment]
Indeed, the call should be attempted instead of going straight for `readURL`.

I am not sure how you'd prefer this to work? `SwaggerLoader.LoadSwaggerFromURIFunc func(loader *SwaggerLoader, url *url.URL) (*Swagger, error)` is probably too weak a prototype to handle "single element URIs".

**Comment by fenollp** [comment]
Thanks to #316 you can now achieve what you want with `(*SwaggerLoader).ReadFromURIFunc` :)
