### ISSUE TITLE
References outside #/components/... fail to parse

### ISSUE THREAD

**Issue by danielgtaylor** [getkin/kin-openapi#24]
As noted in [apisprout#1](https://github.com/danielgtaylor/apisprout/issues/1#issuecomment-408490874) it looks like some references can fail to parse. For example:

```json
{
  "$ref": "#/paths/~1v1~1servers/get/responses/200/content/application~1json/schema/properties/meta"
}
```

will fail to parse but is valid according to [the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#reference-object). Rather than referencing a predefined component it is reusing a piece of another response schema. Ideally the parser would handle these cases regardless of what the link starts with.

**Comment by fenollp** [comment]
I'm all for reviewing a PR fixing this but do not have time to write it :)

**Comment by AbhimanyuG** [comment]
To anyone who's interested, I've posted a bounty for this bug: https://www.bountysource.com/issues/61426741-references-outside-components-fail-to-parse

**Comment by fenollp** [comment]
Is this still an issue now that https://github.com/getkin/kin-openapi/pull/155 is merged?

**Comment by chriswa** [comment]
Yes, it is. There are hardcoded prefixes required on different ref types.

I've added pull request #207 to fix this issue.
