### ISSUE TITLE
JSON Schema discriminator fails to parse

### ISSUE THREAD

**Issue by danielgtaylor** [getkin/kin-openapi#25]
As noted in [apisprout#1](https://github.com/danielgtaylor/apisprout/issues/1#issuecomment-408490874), this [sample file](https://raw.githubusercontent.com/hskrasek/conference-api-docs/master/specs/openapi.yaml) fails to parse because the discriminator is an object instead of a string. It looks like [the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#discriminatorObject) says it should be an object like in the linked example file.

**Comment by fenollp** [comment]
PRs welcomed! Sorry I don't have much time these days...

**Comment by goller** [comment]
@danielgtaylor with my PR in this should now work!
