### ISSUE TITLE
path validation panic when pathItem is nil

### ISSUE THREAD

**Issue by schmilmo** [getkin/kin-openapi#264]
Hi,

If I try to validate the following schema the Paths.Validate function panics because it's accessing pathItem == nil
I used the following schema
```
openapi: 3.0.1
info:
  title: test schema
  description: test schema
  termsOfService: https://www.company.com
  contact:
    name: info
    email: info@company.com
  license:
    name: open-licence
    url: https://www.company.com/open-licence
  version: v3.1.6
servers:
- url: www.company.com
paths:
  /endpoint1/:
```

**Comment by fenollp** [comment]
I doubt this is a valid OpenAPI spec but anyway I agree this call shouldn't panic. 

Please open a quick PR with a nil check and a test that relies on your example. Thanks.

**Comment by fenollp** [comment]
Fixed by https://github.com/getkin/kin-openapi/pull/266
