### ISSUE TITLE
Validating Openapi v3 uspto.yaml is failing due to "Unsupported 'format' value 'uriref"

### ISSUE THREAD

**Issue by heyvister** [getkin/kin-openapi#268]
Hi,

I have tried using _openapi3_ package _Validate_ function and got the above error while validating [https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/uspto.yaml](url) 

- Validation fails on lines L205, L209 -> "format: uriref"

- Using [https://editor.swagger.io/](url) didn't show any issue

Looks like there is similar open issue on APIsprout - [https://github.com/danielgtaylor/apisprout/issues/57](url)

Seems like there is a missing "case", in _func (schema *Schema) Validate(c context.Context) error_  @ schema.go, handling "uriref"

Is there an option to add it  in the following case?
       _case "uri", "uri-reference", "iri", "iri-reference", "uri-template", **"uriref"**:_ ?

Thanks

**Comment by heyvister** [comment]
Seems like there is an expoerted flag _SchemaFormatValidationDisabled_ which disables schema validations

**Comment by fenollp** [comment]
Note: there is no such `uriref` schema format in either the OpenAPIv3 spec nor the [JSON Schema spec](https://json-schema.org/draft/2019-09/json-schema-validation.html).
Maybe you meant `uri-reference`?

In any case, you can disable erroring out on unknown/custom formats with [the flag you cited](https://pkg.go.dev/github.com/getkin/kin-openapi@v0.30.0/openapi3#pkg-variables), as foreign formats are allowed by openapi (which can explain why editor.swagger.io does not complain here).
