### ISSUE TITLE
For validation of request with security schemes are there any default options.AuthenticationFunc

### ISSUE THREAD

**Issue by shivanshudixit16** [getkin/kin-openapi#269]
For validation of request with security schemes are there any default options.AuthenticationFunc or do we need to explicitly pass our own Authentication Function check through RequestValidationInput as done in the tests. Was not able to find any examples or documentation regarding that.

**Comment by fenollp** [comment]
The default is the noop defined at https://github.com/getkin/kin-openapi/blob/26e9a3787488e3608f86913af5fdee929632e3e5/openapi3filter/validation_handler.go#L10

For a more involved example take a look at https://github.com/getkin/kin-openapi/blob/5f67f433f1c41577a27e893ba66c7a6d1a709207/openapi3filter/validation_test.go#L598-L614

Of course if you can share your own implementations the community as a whole would profit. :)

**Comment by shivanshudixit16** [comment]
Thanks ! I am facing issue when i have security set as "api_key" for the swagger pet API example . It fails even if I pass api_key in header , But as per NoopAuthenticationFunc implementation It should not fail, I am just using the code in the README.md i.e, not passing any options.AuthenticationFunc. So I was curious why it was failing .Getting this error `panic: Security requirements failed` .
But it works successfully if I passs something like
`requestValidationInput := &openapi3filter.RequestValidationInput{
		Request:    httpReq,
		PathParams: pathParams,
		Route:      route,
		Options: &openapi3filter.Options{
			AuthenticationFunc: func(c context.Context, input *openapi3filter.AuthenticationInput) error {
				return nil
			},
		},
	}`

**Comment by fenollp** [comment]
Indeed I was wrong: the func is unset in DefaultOptions and so fail-safe. The API consumer must define their own func if they have defined security requirements.
I am mentioning this in the docs.
Thanks!
