### ISSUE TITLE
Not all refs are being resolved

### ISSUE THREAD

**Issue by samschurter** [getkin/kin-openapi#277]
I have the following files, 

`api.yaml`
```yaml
openapi: 3.0.0
info:
  title: automation
  version: 2.0.0
  description: API Documentation
  contact:
    name: placeholder
    email: placeholder
    url: placeholder
tags:
  - name: automation
servers:
  - url: https://api.example.com
    description: Partner - All Others
paths:
  /api/v2/tenants/:
    $ref: './automation/tenants.yaml'
```
`automation/components.yaml` 
```yaml
components:
  schemas:
    rbaScriptParameter:
      title: rbaScriptParameter
      type: object
      properties:
        name:
          type: string
          description: Name of parameter.
        description:
          type: string
          description: Description for parameter.
    rbaScript:
      title: rbaScript
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
```

and `automation/tenants.yaml`
```yaml
summary: Manage scripts by Id
description: This endpoint is used to retrieve and update 
post:
  description: |-
    To update a script:
  tags:
    - automation
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: './components.yaml#/components/schemas/rbaScript'
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            parameters:
              type: array
              items:
                $ref: './components.yaml#/components/schemas/rbaScriptParameter'
```

I'm loading the swagger via 
```go
loader := openapi3.NewSwaggerLoader()
loader.IsExternalRefsAllowed = true
swagger, err := loader.LoadSwaggerFromFile("api.yaml")
```
But the output from `operation.RequestBody.Value.Content.Get("application/json").Schema.Value` is 
```yaml
    schema:
      properties:
        parameters:
          items:
            $ref: ./components.yaml#/components/schemas/rbaScriptParameter
          type: array
      type: object
```

**Comment by samschurter** [comment]
This seems to be related to this line:
https://github.com/getkin/kin-openapi/blob/f05a91328638d7ae73adfd4298cd9456c7692572/openapi3/swagger_loader.go#L628
I followed the code and it IS resolving the references, but when I marshal it back to YAML (with github.com/ghodss/yaml) it only shows a $ref, not the resolved schema. It seems like when the marshaller is hitting the schema, it still has the Ref field AND the Value field in the struct, and it's using the Ref and ignoring the Value.

**Comment by samschurter** [comment]
I added a line after to set `component.Ref = ""` and that solves my problem. However, it breaks the test for #247.

**Comment by fenollp** [comment]
Hey thanks for reporting & looking into it!
I have limited time here but am wondering if you're having the same issue when serializing to JSON (instead of to YAML)? Cheers

**Comment by fenollp** [comment]
Ah! I think I get it now: you'd like to serialize your spec with `$ref`s deref'd and all files merged, right?
Something akin to https://github.com/getkin/kin-openapi/issues/98 ?

**Comment by fenollp** [comment]
You should be able to choose how ref'd structs are serialized by zeroing the `.Ref`
* `x.Ref = ""` will serialize `x` using `x.Value`
* otherwise, `"$ref: '...'"` will be output (given `x.Ref != ""`)
