### ISSUE TITLE
Validation of parameters in the body supported?

### ISSUE THREAD

**Issue by joshi-mohit** [getkin/kin-openapi#281]
Seeing this error with parameter in "body"
"
invalid paths: parameter can't have 'in' value "body" 
"
also in the constants I can see only these type of "in" supported 

const (
--
  | ParameterInPath   = "path"
  | ParameterInQuery  = "query"
  | ParameterInHeader = "header"
  | ParameterInCookie = "cookie"
  | )

Can someoneone help confirm this?

**Comment by fenollp** [comment]
OpenAPI v3 does not allow parameters in body. You must be looking for RequestBody.
