### ISSUE TITLE
Cannot create a useable schema

### ISSUE THREAD

**Issue by schmurfy** [getkin/kin-openapi#288]
I am taking the reverse road most usually take by generating openapi3 documentation from a minimal http framework on top of chi, the start was pretty fast and I can generate everything I need for the request path arguments but I am stuck trying to generate a schema for the `requestBody` of an operation, my best attempt so far is:

```go
type Pet struct {
  Id   string `json:"id"`
  Name string `json:"name"`
}

gen := openapi3gen.NewGenerator()

// bodyField points to `Pet` reflected type
bodySchema, err := gen.GenerateSchemaRef(bodyField.Type)
// error is checked but I removed it for clarity

body := openapi3.NewRequestBody()
body.Content = openapi3.NewContentWithJSONSchema(bodySchema.Value)
bodyRef := &openapi3.RequestBodyRef{
  Value: body,
}

op.RequestBody = bodyRef
swagger.AddOperation(pattern, method, op)
```

Aside from being really verbose (there may be faster way to do things but that's the best I found for now) this works but generates:

```json
{
  "content": {
    "application/json": {
      "schema": {
        "properties": {
          "id": {
            "$ref": "string"
          },
          "name": {
            "$ref": "string"
          }
        },
        "type": "object"
      }
    }
  }
}
```

this cause the viewers to try and request `<my-domain>/string` and i am not sure what I missed, from what I understand internal references should start with "#" but I see no way of influencing what ref are generated and I feel my lack of familiarity with openapi3 does not help xD

Any help or pointer in the right direction will be greatly appreciated :)

**Comment by fenollp** [comment]
What's `openapi3gen`? I'd suggest taking a close look at what it outputs.

When your code doesn't do what you expected, it's simpler to cut it in smaller and smaller parts and to verify what happens v should happen at these boundaries. Start with largeish parts then go finer.

**Comment by schmurfy** [comment]
I don't get your answer, the only reason I wrote a larger piece of my code is to provide context, the only part I have problem with is the generated schema from my object created by `` json in the second block.
What I ideally want for the `requestBody` is (no `$refs` ):
```json
{
  "content": {
    "application/json": {
      "schema": {
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "type": "object"
      }
    }
  }
}
```

The comment on package `openapi3gen`itself confirms it is indeed what I want:
```go
// Package openapi3gen generates OpenAPI 3 schemas for Go types.
```

I want to build an openap schema for my existing structure `Pet`
I even did a test by replacing `$refs` by `type` in the generated output (as shown in the block above) and it worked fine in rapidoc.

**Comment by fenollp** [comment]
Wow haha I did not realize this package was part of this very repo!
So yeah I'm not familiar with this but looking at the docs I think you should have better luck using [`NewSchemaRefForValue`](https://godoc.org/github.com/getkin/kin-openapi/openapi3gen#NewSchemaRefForValue).
See the tests for example usage (a tip to beginners: *always look at the tests*):
https://github.com/getkin/kin-openapi/blob/d4df86a63c4efbaf31aabce8f39555f22a8f1b30/openapi3gen/openapi3gen_test.go#L25-L61

**Comment by schmurfy** [comment]
I did have a look at `NewSchemaRefForValue` but failed to use it on first try, I had another look and found my solution.
The key was:
```go
  for ref := range gen.SchemaRefs {
    ref.Ref = ""
  }
```

After removing the refs it generates what I expected.

This package is nice but finding your way around is not that intuitive especially when I feel like one of the very few to generate schema from code instead of the opposite xD

**Comment by fenollp** [comment]
PRs welcomed. If you can open a PR with your example code as a test or as an example I'll get it merged.
