### ISSUE TITLE
Support openapi extensions in proper resources

### ISSUE THREAD

**Issue by sergicastro** [getkin/kin-openapi#299]
Even [openapi extensions specific documentation](https://swagger.io/docs/specification/openapi-extensions/) enumerates a list of allowed places where extensions can be used, there are more resources that can support them, for example, Servers as [its specific documentation shows](https://swagger.io/specification/#server-object).

Current kin-openapi version 0.39.0 supports extensions in the resources described in openapi extensions doc.

But would be useful to expand extensions to the rest of the resources that support them.

Note: This applies to v2.0 and v3.0 specs.

**Comment by fenollp** [comment]
Could you be more specific?
Did you notice https://pkg.go.dev/github.com/getkin/kin-openapi@v0.39.0/openapi3#ExtensionProps
What do you feel is missing, exactly (an example?)?

**Comment by sergicastro** [comment]
I guess, support extensions in the missing resources just requires the structs to extend `ExtensionsProps`, right?
I could take I look.

**Comment by sergicastro** [comment]
@fenollp thanks for your quick work. I added extensions to a few missing resources.
