### ISSUE TITLE
$ref not expanded by swagger loader

### ISSUE THREAD

**Issue by norbertstrzelecki** [getkin/kin-openapi#300]
Hi Folks, thanks for the awesome lib!

I've checked many issues here but not found the resolution. Could you please give me any hint on how to resolve (expand) the `ref$`  field in the code below? As far as I understand, it should be resolved automatically, but the output is not so.

I try to compare two JSONs, one parsed from the `openapi.yaml` with the second one generated from some `struct` (far below):

```yaml
# openapi.yaml
(...)
components:
  schemas:
    Graph:
       type: object
       properties:
         Name:
           type: string
         Items:
           type: array
           items:
             $ref: '#/components/schemas/GraphItem'
     GraphItem:
       type: object
       properties:
         Label:
           type: string
         Color:
           type: string
         Length:
           type: integer
         SubCategory:
           type: string
         Index:
           type: integer
         Id:
           type: string
```
So after parsing it as follows:
```golang
data, _ := ioutil.ReadFile("./openapi.yaml")

loader := openapi3.NewSwaggerLoader()
// doesn't matter if I load it directly using LoadSwaggerFromFile() 
swagger, _ := loader.LoadSwaggerFromData(data)

graph := swagger.Components.Schemas["Graph"].Value.Properties
j, _ := json.MarshalIndent(graph, "", "  ")
fmt.Println(string(j))
```
I got, as I understand it, an unresolved `ref$`:
```json
 {
  "Items": {
    "items": {
      "$ref": "#/components/schemas/GraphItem"
    },
    "type": "array"
  },
  "Name": {
    "type": "string"
  }
}
```
I could add to the above snippet `graph["Items"].Value.Items.Ref = ""`, but there must be some more "elegant" way.

**What I would like to get is the "resolved" JSON as when I generate it from this `struct` using `openapi3gen`:**
```golang
// Graph structure
type Graph struct {
    Name  string `json:"Name"`
    Items []GraphItem `json:"Items"`
}

// GraphItem structure
type GraphItem struct {
    Label       string `json:"Label"`
    Color       string `json:"Color"`
    Length      int32 `json:"Length"`
    SubCategory string `json:"SubCategory"`
    Index       int32 `json:"Index"`
    ID          string `json:"Id"`
}
```
Generating:
```golang
schema, _, _ := openapi3gen.NewSchemaRefForValue(&Graph{})
j, _ := json.MarshalIndent(schema.Value.Properties, "", "  ")
fmt.Println(string(j))
```
**Output:**
```json
 {
  "Items": {
    "items": {
      "properties": {
        "Color": {
          "type": "string"
        },
        "Id": {
          "type": "string"
        },
        "Index": {
          "format": "int64",
          "type": "integer"
        },
        "Label": {
          "type": "string"
        },
        "Length": {
          "format": "int64",
          "type": "integer"
        },
        "SubCategory": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "type": "array"
  },
  "Name": {
    "type": "string"
  }
}
```

BTW is there any way of generating that JSON without tagging the struct fields with `json:"..."` tags? 

Thanks for any help!

**Comment by Oioio** [comment]
Hello.
I guess my problem is related to this issue.
I want to get "flat" openapi.json (without any $ ref's). I've could traverse the document and clear all Ref's manually.
But, there is another way to do this?

**Comment by fenollp** [comment]
There is of course no way of doing this other than traversing the doc and this lib doesn't implement this functionality... yet! You are welcome to open a PR. I'll review it for sure.

Do note that not all documents can be "flattened" (all `$ref` removed): `$ref` cycles are possible.
