### ISSUE TITLE
References to callback components are not resolved

### ISSUE THREAD

**Issue by reuvenharrison** [getkin/kin-openapi#301]
My spec contains a reference to a callback:
```yaml
paths:
  /register:
    post:
      summary: Subscribe to a webhook
      callbacks:   # Callback definition
        myEvent:   # Event name
          $ref: '#/components/callbacks/myEvent'
```
After loading the spec with LoadSwaggerFromURI, the value is nil:
```
<github.com/getkin/kin-openapi/openapi3.CallbackRef>
Ref:"#/components/callbacks/myEvent"
Value:nil <*github.com/getkin/kin-openapi/openapi3.Callback>
```
Proposed resolution:
func ResolveRefsIn should resolve callbacks.

**Comment by fenollp** [comment]
Indeed callbacks resolution is not yet done. Thanks for taking the time of reporting!
You can take a look at `resolvePathItemRef` in https://github.com/getkin/kin-openapi/blob/master/openapi3/swagger_loader.go
I'll gladly review any PR sent my way :)
