### ISSUE TITLE
What happened to `openapi3filter.NewRouter(spec)`?

### ISSUE THREAD

**Issue by jeffwidman** [getkin/kin-openapi#326]
#210 migrated `openapi3filter.NewRouter()` to `openapi3filter.NewRouter(spec)` [according to the changes in the `README`](https://github.com/getkin/kin-openapi/pull/210/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R56). 

However the compiler is complaining that `openapi3filter` doesn't declare `NewRouter()`... and indeed, i don't see it documented here at all? https://pkg.go.dev/github.com/getkin/kin-openapi@v0.51.0/openapi3filter

How do I instantiate a new router?

May also be good to add a note to the bottom of the README under the section **Sub-v0 breaking API changes** since this func signature change was a breaking change (and to be clear, I'm fine with breaking changes, as long as it's clear how I can still use it...)

**Comment by fenollp** [comment]
Ah somehow I completely missed on updating the readme! Sorry about this. 

In the meantime you'll find a way to use the router under the routers/legacy directory.

**Comment by mikeschinkel** [comment]
I am seeing that the compiler also complains about these being undefined too:

```
openapi3filter.Router
openapi3filter.RouteError
```

**Comment by jeffwidman** [comment]
Thanks for the helpful docs!

**Comment by fenollp** [comment]
Thanks for reporting :)
