### ISSUE TITLE
Vaidating an instance of data against a loaded OpenAPI document

### ISSUE THREAD

**Issue by philsturgeon** [getkin/kin-openapi#33]
Hey, I would like to be able to look up an operation by method and URL, then confirm a real response body (instance of data) conforms to one of the response bodies defined on the OpenAPI v3.0 operation. Is this possible with your package ?

**Comment by fenollp** [comment]
Not my project & haven't had the time to try what you want to do but I'll eventually do it.
Here's probably what you want: https://godoc.org/github.com/getkin/kin-openapi/openapi3filter#ValidateResponse
You can also read the code since, you know, this is open source.

**Comment by fenollp** [comment]
Hi there, please have a look at https://github.com/getkin/kin-openapi#validating-http-requestsresponses

**Comment by fenollp** [comment]
The `openapi3filter` package should be the solution here.
Please re-open if you still have issues.
