### ISSUE TITLE
Document breaking change removing openapi3filter.RequestError.[Status|HTTPStatus()]

### ISSUE THREAD

**Issue by jeffwidman** [getkin/kin-openapi#332]
In https://github.com/getkin/kin-openapi/pull/325/files#diff-58daf090b2a3ffdfaa90f65cfc824e95cb5df1481111b6ee21b6bffdcbd7881eL35-L36 both `Status` and `HTTPStatus()` were removed from the public API of `openapi3filter.RequestError`.

Given that this is a breaking change, this should probably be documented on the Readme under the breaking changes section.

I assume I should now always just use `http.StatusBadRequest`?

**Comment by fenollp** [comment]
`openapi3filter.RequestError.Status` was never set so I guess you can just use that yes.
What was your use of this field?

**Comment by jeffwidman** [comment]
We were just returning the Status to the caller and relying on whatever this lib was using... so I'll just use `http.StatusBadRequest` and it'll be fine.
