### ISSUE TITLE
openapi3filter.RegisterBodyDecoder() / openapi3filter.UnregisterBodyDecoder() based on singleton

### ISSUE THREAD

**Issue by wtask** [getkin/kin-openapi#339]
The subject is ugly mostly for tests. If one test needs custom decoder, but another expects to use original one this case is sucks.

As a protection, you can offer a function to obtain a registered decoder so that it can be restored ...

**Comment by fenollp** [comment]
Could you show in code what you are suggesting please?

**Comment by wtask** [comment]
Something like
```
originalDecoder := openapi3filter.GetBodyDecoder({contentType})
openapi3filter.RegisterBodyDecoder({contentType}, {customDecoder})
...
openapi3filter.RegisterBodyDecoder({contentType}, {originalDecoder})
```
Or offer default decoder registry, which will be used to fill in used decoders
```
openapi3filter.RegisterBodyDecoder({contentType}, openapi3filter.DefaultBodyDecoder({contentType}))
```
