### ISSUE TITLE
External references are set to nil if response to remote fails with http != 200

### ISSUE THREAD

**Issue by steffakasid** [getkin/kin-openapi#343]
I've a swagger document with an external reference. Like this:
```
paths:
  /pet:
    $ref: 'http://localhost:1080/some/path/ref.yaml'
```
Currently I mock this dependency via MockServer. When the MockServer isn't running. The swagger loading panics, which is finde I think. But when I do not load the expectation to return the content of ref.yaml, so MockServer just returns an HTTP 403 I don't get any error, the reference is just noch replaced. Is there any possibility to throw an error if the reference couldn't be loaded correctly?

Regards
Steffen

**Comment by steffakasid** [comment]
I had a look at the code:
```
func (swaggerLoader *SwaggerLoader) readURL(location *url.URL) ([]byte, error) {
	if f := swaggerLoader.ReadFromURIFunc; f != nil {
		return f(swaggerLoader, location)
	}

	if location.Scheme != "" && location.Host != "" {
		resp, err := http.Get(location.String())
		if err != nil {
			return nil, err
		}
		defer resp.Body.Close()
		return ioutil.ReadAll(resp.Body)
	}
	if location.Scheme != "" || location.Host != "" || location.RawQuery != "" {
		return nil, fmt.Errorf("unsupported URI: %q", location.String())
	}
	return ioutil.ReadFile(location.Path)
}
```

There is no validation on the response status code!

**Comment by fenollp** [comment]
PRs welcomed :)

**Comment by steffakasid** [comment]
:) no Problem: https://github.com/getkin/kin-openapi/pull/345

I added jarcoal/httpmock in order to test this. Not sure if there is an easier way to do it.
