### ISSUE TITLE
Cannot import gorillamux based router

### ISSUE THREAD

**Issue by jimkoen** [getkin/kin-openapi#353]
Hello,
when I try to import the gorillamux based router via 
```golang
import (
    "github.com/getkin/kin-openapi/openapi3"
    "github.com/getkin/kin-openapi/routers/gorillamux"
)
```
my IDE (Goland 2020.3) claims that it cannot resolve the gorillamux file (Error: `Cannot resolve file 'gorillamux'`).

However if I import the legacyrouter via

```golang
import (
    "github.com/getkin/kin-openapi/openapi3"
    "github.com/getkin/kin-openapi/routers/legacy"
)
```
it works just fine, and resolves submodules as well.

Does anyone have an idea why this might be?

**Comment by fenollp** [comment]
Not sure what's going on here as #354 shows.
Maybe you need to
```
go get github.com/getkin/kin-openapi/routers/gorillamux
```
in the directory where your go.mod lives.

**Comment by jimkoen** [comment]
> Not sure what's going on here as #354 shows.
> Maybe you need to
> 
> ```
> go get github.com/getkin/kin-openapi/routers/gorillamux
> ```
> 
> in the directory where your go.mod lives.

I have tried that, but it doesn work. The full code is as follows, maybe someone can help:

```golang
package app

import (
    "github.com/getkin/kin-openapi/routers/legacy"
    "github.com/gorilla/mux"
    "net/http"
    "github.com/getkin/kin-openapi/openapi3"
    "github.com/getkin/kin-openapi/routers/gorillamux"


)

func Start(){


    loader := openapi3.NewLoader()
    doc, _ := loader.LoadFromFile("../api/openapi.yaml")
    _ = doc.Validate(loader.Context)
    router, _ := gorillamux.NewRouter()

    r := mux.NewRouter()
    r.HandleFunc("/", func(writer http.ResponseWriter, request *http.Request) {
        writer.Write([]byte("Hello World!"))
    })

    http.Handle("/", r)
}

```

**Comment by fenollp** [comment]
> I have tried that, but it doesn work.

Please be most specific. What error message do you get on `go get`?
