### ISSUE TITLE
Use more descriptive struct name than `T` (formerly `Swagger`)

### ISSUE THREAD

**Issue by grokify** [getkin/kin-openapi#358]
I just noticed that the `Swagger` struct was renamed to `T` in `v0.61.0` / PR https://github.com/getkin/kin-openapi/pull/351

Would it be possible to use a more descriptive name? Perhaps something like `Specification`?

`T` is documented here with the following description:

> T is the root of an OpenAPI v3 document

https://pkg.go.dev/github.com/getkin/kin-openapi@v0.61.0/openapi3#T

It seems `Specification` would be easier to understand. `Document` would be ok but with less context. `T` seems more difficult to comprehend and unusual as no other public struct name uses a single letter.

**Comment by fenollp** [comment]
Hello there, thanks for raising concerns. If you feel like something is under documented I'm happy to oblige and/or review PRs.
I agree renaming a couple types is quick however I'm afraid that ship has sailed.

> T seems more difficult to comprehend and unusual as no other public struct name uses a single letter.

I fail to see your points there. The std lib has plenty of single letter names.

Again, thanks for discussing. We can always better document things and I'll happily help with that.

**Comment by grokify** [comment]
Can you explain why `T` was chosen? 

Although the document describes it as "T is the root of an OpenAPI v3 document", "T" does not seem to represent "OpenAPI" or "Document"?

Was `T` chosen because it was present the tests a `testing.T`?

This is described as:

> T is a type passed to Test functions to manage test state and support formatted test log

https://golang.org/pkg/testing/#T

**Comment by grokify** [comment]
To use a more descriptive name than `T` in my code, I use an alias now such as the following:

`type Spec = openapi3.T`

This way, I can refer to `Spec` in my code instead of `openapi3.T`.
