### ISSUE TITLE
router.FindRoute fails when there is a comma between path parameters

### ISSUE THREAD

**Issue by exgphe** [getkin/kin-openapi#364]
e.g.

```yaml
/data/example-jukebox:jukebox/library/artist={name},{id}:
    get:
      tags:
      - example-jukebox
      summary: returns example.jukebox.jukebox.library.Artist
      description: |-
        Represents one 'artist' resource within the
                           'jukebox' library resource.
      parameters:
      - name: name
        in: path
        description: name of artist
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: Id of artist
        required: true
        schema:
          type: string
      responses:
        "200":
          description: example.jukebox.jukebox.library.Artist
          content:
            application/yang-data+json:
              schema:
                $ref: '#/components/schemas/example.jukebox.jukebox.library.ArtistWrapper'
```

When trying to `router.FindRoute(request)` for operations such as "GET /data/example-jukebox:jukebox/library/artist=abc,123", the method would fail and returns a `routers.ErrPathNotFound` error

**Comment by exgphe** [comment]
A temporary fix would be https://github.com/exgphe/kin-openapi/commit/0ac61f6fc219f4b3e9993b8944842b0727600a75 and https://github.com/exgphe/kin-openapi/commit/2638c299a8cb79fa5d4214d85fa0d55258c2bf60 . However these fixes are too hacky and are very likely not touching on the root cause of this problem.

**Comment by fenollp** [comment]
In the meantime maybe you can have a go at the other provided router https://pkg.go.dev/github.com/getkin/kin-openapi@v0.62.0/routers/gorillamux

**Comment by fenollp** [comment]
The legacy router is deprecated. Please turn to the gorilla/mux one
