### ISSUE TITLE
gorillamux.NewRouter fails if any servers url contain variable for port number of the url

### ISSUE THREAD

**Issue by karupanerura** [getkin/kin-openapi#367]
e.g.

```yaml
openapi: "3.0.0"
servers:
  - url: http://127.0.0.1:{port}/
    variables:
      port:
        default: '8000'
```

It throws error at https://github.com/getkin/kin-openapi/blob/v0.63.0/routers/gorillamux/router.go#L41

```
parse "http://127.0.0.1:--------------------------------------------------port__________________________________________________": invalid port ":--------------------------------------------------port__________________________________________________" after host
```

**Comment by fenollp** [comment]
Ah yes this is related to https://github.com/getkin/kin-openapi/pull/337 and the issue it attempts to solve.
In my mind there isn't a perfect solution to this as it relies on `url.Parse`'s leniency. A good enough solution might be to use the default value of variables in the host but then your `port` will only ever match `8000`. Which is fine as long as it is documented I guess.

**Comment by karupanerura** [comment]
Thank you for the kind reply. My understanding is almost exactly the same as yours.

In my opinion, `url.Parse` is only intended to validate the URL format. So, I think that creating a URL string using the default value of variables in the host and validating it will serve the purpose.
Next, `(*mux.Route).Host` method [can accept the OpenAPI 3.0 servers URL template syntax(by accident)](https://pkg.go.dev/github.com/gorilla/mux#Route.Host). So, I think it can pass the host section of the template directly to this method.
I think it can solve this issue.

If this idea is good for you, I can send you a patch. What do you think?

**Comment by slessard** [comment]
Now I've hit this problem. @karupanerura I'd be interested in trying out a patch if you have one

**Comment by fenollp** [comment]
I've opened https://github.com/getkin/kin-openapi/pull/524 that handles this specific issue.

@slessard Your PR (at this time) may solve this issue but it uses defaults for all variables not just this one specific case of port vars and so is not backwards compatible.

@karupanerura @slessard please give feedback
If you guys are happy with it I'll merge this and close https://github.com/getkin/kin-openapi/pull/523

**Comment by slessard** [comment]
Sorry for the delay. I am looking at this now
