### ISSUE TITLE
Let's remove package 'jsoninfo'

### ISSUE THREAD

**Issue by jban332** [getkin/kin-openapi#37]
Historical background: The package `jsoninfo` was created with the goal of having elegant serialization.
 
The fact that `jsoninfo` resides in this repository is just a historical accident. The code is just an internal implementation detail to this project. So I created [github.com/getkin/happyjson](https://github.com/getkin/happyjson) and refactored it a bit.

If there are no objections, I'll replace `jsoninfo` with the external package `happyjson`. Any feedback about how _kin-openapi_ implements serialization internally is welcome.

**Comment by fenollp** [comment]
Fine by me.

**Comment by fenollp** [comment]
happyjson doesn't seem to exist. Swagger/openapi2 projects seem to be using easyjson, if this can help unification...
