### ISSUE TITLE
[Question] Auto generate swagger.json from go code

### ISSUE THREAD

**Issue by kishaningithub** [getkin/kin-openapi#380]
I would like to auto generate swagger documentation from existing go code.

Any pointers/examples would be great.

**Comment by kishaningithub** [comment]
https://mariocarrion.com/2021/05/02/golang-microservices-rest-api-openapi3-swagger-ui.html

This blog seems to provide a good example..

**Comment by felixvd** [comment]
I am trying to generate an OpenAPI3.0 description from Go code, and was pleased to read in the example that it should be possible with this package. But the example (or rather the output of simply calling `yaml.Marshal` on the `openapi3.T` type) does not seem to generate an OAS-compliant document. It looks more like this:

```
extensionprops: {}
openapi: ""
info: null
paths:
  /environment/:
    extensionprops: {}
    summary: List or create environments
    get:
      extensionprops: {}
      description: This is a list operation
      parameters:
      - ref: limitFilterParam
        value:
          extensionprops: {}
          name: limit
          in: query
          description: The maximum amount of results to return.
          style: form
          allowEmptyValue: true
          schema:
            ref: regularIntegerSchema
            value:
              extensionprops: {}
              type: integer
          example: 3, 5, 10...
      requestBody:
        ref: ""
        value: null
      responses: {}
    post:
      extensionprops: {}
      description: This is a Create operation
      responses: {}
  /environment/{environmentId}/:
    extensionprops: {}
    summary: Copy, get, peek, modify or delete one environment
    get:
      extensionprops: {}
      description: This is a Get operation
      responses: {}
[...]
```

I haven't looked into it, but I am assuming that _either_ the `Ref` or `Value` field (not both) are filled during parsing, and only one of them should be exported to a document. 

I am assuming that a `Generator` class for paths needs to be written to make the output OAS3-compliant, since the Readme only mentions schemas as a possible output. Would be happy to hear the input of a maintainer on if this has been worked on before or how this might be most efficiently done (@fenollp )

**Comment by fenollp** [comment]
Please have a look at the examples in https://pkg.go.dev/github.com/getkin/kin-openapi@v0.86.0/openapi3gen

> I haven't looked into it, but I am assuming that either the Ref or Value field (not both) are filled during parsing, and only one of them should be exported to a document.

Well do take a look. It's open source. You're right `XyzRef` types are unions and prefer `Ref` field when serializing.

I'm not sure I understand your last paragraph. Maybe you can share some of your code with us.

**Comment by felixvd** [comment]
That phrase was missing a "yet"! I am planning to take a closer look tomorrow. You say the `XyzRef` types prefer `Ref` when serializing, but the serialization in my last post printed both fields. Am I overlooking another way to serialize them?

> I'm not sure I understand your last paragraph.

The `Generator` code you linked only converts `reflect.Type`s to schemas, as the package description also explains. But my goal is to generate a complete OpenAPI3.0 description including schemas and paths. It seems that there's no way to export a OAS3-compliant YAML or JSON document, so I assume another class needs to generate it from an `openapi3.T` object.

> Maybe you can share some of your code with us.

I'll see if I can isolate an example.

**Comment by fenollp** [comment]
It sounds like you are relying on a YAML package that does not use the `JSONMarshaller` interface. Which do you use?

(There are no classes in Go.)

Yes see about that.

**Comment by fenollp** [comment]
I think you're hitting https://github.com/getkin/kin-openapi/issues/241

**Comment by felixvd** [comment]
Yes, it looks like it. My import was `gopkg.in/yaml.v2` and it worked fine with `github.com/ghodss/yaml`. The output from before now looks like this:

```yaml
components: {}
info: null
openapi: ""
paths:
  /environment/:
    get:
      description: This is a list operation
      parameters:
      - $ref: limitFilterParam
      requestBody: null
      responses: null
    post:
      description: This is a Create operation
      responses: null
    summary: List or create environments
  /environment/{environmentId}/:
    get:
      description: This is a Get operation
      responses: null
    summary: Copy, get, peek, modify or delete one environment
```

That looks perfectly fine, what a relief. I will keep working with this for now.

I wasn't aware that the package did this, by the way. It would be worth spelling this out on the Readme and giving an example. I thought it would need a lot more hacking.
