### ISSUE TITLE
Support integer as string in openapi3 schema validation

### ISSUE THREAD

**Issue by eagami9** [getkin/kin-openapi#384]
In our project we use a given schema where a property is defined as int(64 in this case).
Also in this project, we need to support migrating data from the old and already released product, where it exports this property as string, e.g.: "2000000001". 
`visitJSONString` is failing right away when type is not as expected, while a simple strcov.Atoi could redirect it to `visitJSONNumber` (optionally somehow?).

**Comment by fenollp** [comment]
Sounds like you're looking for oneOf. See https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

**Comment by eagami9** [comment]
With a "given schema" I meant it's not something that would be easy to change.
If I would to write this property schema, it would probably be oneOf.
