### ISSUE TITLE
Validation does not work when using a base path and multiple servers not explicitly declared

### ISSUE THREAD

**Issue by rtfpessoa** [getkin/kin-openapi#385]
Hi,

I have an API with a base path (e.g.: `/v1`) and i have multiple dns's pointing to it that are not known at build time.

Since I do not care about validating the dns/url my initial try was to put an empty server list, the problem is that since I have a base path it will try to match `/v1/endpoint` with just `/endpoint`.

Any ideas on how to fix this?

Also would you be open to a contribution that allows the configuration for skipping the validation for the dns part and just checks paths?

**Comment by fenollp** [comment]
I'm not sure what DNS validation you're talking about. Can you maybe share a bit more of your code/openapi document?

**Comment by rtfpessoa** [comment]
Sorry for not being clear enough I will try to make a better example.

Imagine you have an API with the current spec where we can have multiple servers that are not known at build time.

```
openapi: 3.0.1
info:
  title: My API
# servers:
#    - url: "https://api.company.com/v1"
#    - url: "https://api2.company.com/v1"
paths:
  /one/endpoint:
    get:
      responses:
        "200":
          description: "Success"
```

This means that the endpoint is available at both `https://api.company.com/v1/one/endpoint` and  `https://api2.company.com/v1/one/endpoint`.

The problem I have is:
- If I have an empty list of servers in the spec, since the API has a base path of `/v1`, it will try to match the path `/v1/one/endpoint` instead of the one without `/v1` since it has no way to know this exists.
- If I pass one server it will match the whole URL including the hostname/dns, which means that even if I know the name of one server it will fail to validate the requests from the other.

I would like to overcome this, and my suggestion would be to allow to skip the validation of the hostname/dns, in this case `api.company.com` or `api2.company.com` so that I would pass the url for the sake of the path only.

Does it make more sense?

**Comment by fenollp** [comment]
Once your openapi document is deserialized into `doc` and before calling `doc.Validate(ctx)` you can just reset `doc.Servers` to something that fits your needs: for instance a test server, a local host, ...

You could also just loop on `doc.Paths` and modify said paths so as to prepend `"/v1"`. 

There isn't really a DNS validation as you call it: `doc.Validate(ctx)` does not perform network calls.

**Comment by rtfpessoa** [comment]
> Once your openapi document is deserialized into doc and before calling doc.Validate(ctx) you can just reset doc.Servers to something that fits your needs: for instance a test server, a local host, ...

The problem is that I still do not know the servers at that time and if I put anything that is not an exact match it fails. And I cannot see the advantage of validating the hostname in the URL.

> You could also just loop on doc.Paths and modify said paths so as to prepend "/v1".

That is an option but sounds like a weird solution since everything else supports base path, even the code generation.

> There isn't really a DNS validation as you call it: doc.Validate(ctx) does not perform network calls.

I meant hostname validation.

**Comment by rtfpessoa** [comment]
If there is anyway you think this could be changed or improved let me know, I would love to contribute it.

**Comment by fenollp** [comment]
I'm still unsure I understand the issue you're experimenting. `doc.Validate(ctx)` does not do hostname validation AFAIK. Are you using something else? Do you mind sharing some code?
There is no code generation in this lib, except maybe `openapi3gen`. Are you conflating different libs here?

**Comment by rtfpessoa** [comment]
@fenollp it is my fault you are not understanding. I am talking about the validation middleware available in `oapi.OapiRequestValidatorWithOptions`.

**Comment by rtfpessoa** [comment]
Same as the other ticket. I am sorry for the confusion

**Comment by rtfpessoa** [comment]
After more digging I finally got to the root of the issue and it was in this project too.
What I was looking for was the method `FindRoute` in here https://github.com/getkin/kin-openapi/blob/master/routers/legacy/router.go#L121. This line enforced the host of the url and that was the problem.

But the new router seems to have this fixed, but I still need to test.

**Comment by rtfpessoa** [comment]
After some more tests seems like it is still enforced.
The workaround I did was `swagger.Servers[0].URL = "https://" + apiBasePath` before instantiating the validator. This way it will not check the host.

**Comment by hhhapz** [comment]
A helpful note for anyone who might face this in the future: the server url can only contain a base path, so you could, for example, assign `URL` to just `/v1`.
