### ISSUE TITLE
[Question]: Intentional cycles in structs

### ISSUE THREAD

**Issue by DerekStrickland** [getkin/kin-openapi#387]
We have a struct in our project that allows us to do recursive diffs on arbitrary objects. It is defined as this.

```
type ObjectDiff struct {
	Type    DiffType
	Name    string
	Fields  []*FieldDiff
	Objects []*ObjectDiff
}
```

This allows users to perform a dry-run type operation against the API to see what would change if they were to actually submit the operation.

When trying to use kin to generate an  OpenAPI spec, this, of course, throws a CycleError.  Is there any existing feature or configuration option that can allow us to detect the cycle and keep on processing without the infinite recursion?

**Comment by DerekStrickland** [comment]
Short of that, I'm wondering if it is naive to just return the parent ref [here](https://github.com/getkin/kin-openapi/blob/bde5325550db1fa371168738ec29331e4f646795/openapi3gen/openapi3gen.go#L88) if a cycle is detected.  Maybe I could add an option like useAllExportedFields so people have to opt into this behavior.

**Comment by fenollp** [comment]
openapi3gen does cycle detection but doesn't do mitigation (yet).

The only way around cycles that I see is to have openapi3gen define schemas under #/components and use $ref.s each time a schema is mentioned.

If you're going down this path I'd gladly help in reviewing & API design.

**Comment by DerekStrickland** [comment]
I am going down this path for sure. How best would you like to collaborate? Async seems a little challenging for something this abstract, but I'll give it a shot if that our only option.
