### ISSUE TITLE
Any way to get more detailed errors

### ISSUE THREAD

**Issue by rtfpessoa** [getkin/kin-openapi#390]
Hi,

When using the `oapi.OapiRequestValidatorWithOptions` is there a way to get a more detailed error?

When I have a parameter which is an enum and the value passed is not in the enum would be great to know the field failing the validation.

Instead I get a huge message about the whole schema:
```plaintext
{"error": "code=400, message=Request body has an error: doesn't match the schema: Doesn't match schema \"oneOf\", internal=Request body has an error: doesn't match the schema: Doesn't match schema \"oneOf\"\nSchema:\n  {\n    \"description\": \"Details of an event.\",\n    \"oneOf\": [\n      {\n        \"$ref\": \"#/components/schemas/Deployment\"\n      },\n      {\n        \"$ref\": \"#/components/schemas/Change\"\n      },\n      {\n        \"$ref\": \"#/components/schemas/Incident\"\n      }\n    ],\n    \"type\": \"object\"\n  }\n\nValue:\n  {\n    \"$type\": \"incidenta\",\n    \"incident_id\": \"1627554151\",\n    \"source\": \"api\",\n    \"time_created\": \"2021-07-29T09:10:00Z\",\n    \"time_resolved\": \"2021-07-29T09:10:00Z\"\n  }\n"}
```

In this case only the field `$type` is wrong not the whole object.
Also would be even better if we could let people know what are the valid options.

Any idea if any of this is possible or if this could even be implemented? I would be up to help if some pointers are provided.

**Comment by fenollp** [comment]
#230 should change the schema validation code and bring more detailed errors.

I'm not sure what you mean with `OapiRequestValidatorWithOptions`: git-grep'ing returns nothing.

> Also would be even better if we could let people know what are the valid options.

We can always write more documentation :)

**Comment by rtfpessoa** [comment]
Now I see the problem. I am in the wrong project. :man_facepalming: 
I need to ask this in `github.com/deepmap/oapi-codegen`

I am sorry for the confusion

**Comment by rtfpessoa** [comment]
After more digging seems like github.com/deepmap/oapi-codegen is using this project after all for the validation of the requests.

The code to do the validation is around here https://github.com/getkin/kin-openapi/blob/master/openapi3/schema.go

Do you think it would be possible to add more details as I was looking for above? Would it be worth looking deeper?

**Comment by fenollp** [comment]
I mean, now I'm curious.

**Comment by kevin-postman** [comment]
Me too.. as I had a previous issue with trying to get line specific details of an error when it's returned. Not sure that is possible.. but the more details, especially if it can be parsed by the consuming caller in a way that could say.. be helpful to allow more specific information provided back to the client.. that would be fantastic. Line number, position in line, and so forth would all be helpful.

**Comment by rtfpessoa** [comment]
My idea would be to try to add the name of the field with the problem and ideally the schema affected.
But I do not know the code so I would have to dig a bit deeper. That was why I was asking @fenollp if you had any insight into why this was not done. If it was just hard, or impossible with the current implementation.

**Comment by rtfpessoa** [comment]
I went ahead and navigated and the code and the problem is not the messages.
It seems to happen in my specific use case of the `oneOf` where the validator would get possibly N errors and in the current scenario it discards them and just says it does not fulfil the `oneOf` rule.

I now have a better understanding about this and I think this decision is ok. But I believe that it could really help the person getting the validator output to know more about the failure. 

@fenollp what do you think about returning either the last error or returning all the errors?

**Comment by rtfpessoa** [comment]
@fenollp I did an experiment here https://github.com/getkin/kin-openapi/pull/394/files

What do you think?

**Comment by rtfpessoa** [comment]
@fenollp after that PR seems like I still have some vague messages cause by the `failfast` parameters.

Can you explain or provide some context why it is used internally?

**Comment by fenollp** [comment]
`failfast` when returns "a very cheap to build error" instead of something more involved. I'm unsure this still holds any truth today and will probably disappear with the new schema lib I mentioned on the PR.
Feel free to skip the failfast logic in the context of the oneOf :)
