### ISSUE TITLE
Cannot validate path parameters encoded with new router

### ISSUE THREAD

**Issue by rtfpessoa** [getkin/kin-openapi#397]
Hi, 

My paths are not being validated correctly with the new mux router.

Seems like the problem is here https://github.com/getkin/kin-openapi/blob/master/routers/gorillamux/router.go#L59

Any reason to not use the encoded path originally?

e.g.:

`/my/pa%2Fram/path` should match the route `/my/{param}/path` but it does not.

**Comment by fenollp** [comment]
Sounds like an issue specific to the encoding of `/` being `%2F`.

If you can use the originally encoded path and solve this issue for you I can help you with the pull request.

**Comment by rtfpessoa** [comment]
@fenollp Not sure I got exactly what you meant, but I got a PR working.
