### ISSUE TITLE
Why is an Authentication Function necessary for paths with security schemes?

### ISSUE THREAD

**Issue by BananaNosh** [getkin/kin-openapi#401]
I might have misunderstood the intention of the **RequestValidation**.
In my opinion its task is to check that users of the OpenApi use requests that are correct w.r.t. the OpenApi definition.

With this in mind I do not understand why for paths with **security schemes** it is mandatory to have a Authentication Function within the options to pass the validation for a corresponding request.
As this is a validation of the server being written correctly, not of the request made.

Should'nt the developer of the server be responsible for implementing the authentication.
For example in combination with _echo_ the validation does not work as intended for security schemes.

I would be glad, if somebody could explain, why this is a feature.

**Comment by fenollp** [comment]
> Should'nt the developer of the server be responsible for implementing the authentication.

Of course, that's why https://pkg.go.dev/github.com/getkin/kin-openapi@v0.74.0/openapi3filter#AuthenticationFunc is provided as well as https://pkg.go.dev/github.com/getkin/kin-openapi@v0.74.0/openapi3filter#NoopAuthenticationFunc

This is just a place to plug the developer's auth implementation.

**Comment by marmiha** [comment]
It is also wierd to me, as I have yet not found any way of actually injecting anything in the request context that lives to see the endpoint handlers.

It seems for now that it's only to check the validity of the schemes.

**Comment by marmiha** [comment]
This can be a good reference:

https://github.com/deepmap/oapi-codegen/blob/master/examples/authenticated-api/echo/server/jwt_authenticator.go
