### ISSUE TITLE
If servers.url does not contain `://` the schemes match will fail

### ISSUE THREAD

**Issue by sljeff** [getkin/kin-openapi#410]
If there is a yaml like this:
```yaml
servers:
- url: /abc
``` 

Then Validator must fail. Because schemes are parsed as `[]string{"/abc"}`.

---

According to the example in the `Server URL Format` subsection of [OpenAPI document](https://swagger.io/docs/specification/api-host-and-base-path/), `/` `/v1/reports` are also legal URLs.

> Although the `scheme://host[:port][/path]` above is inconsistent, many places that don't require scheme and host validation already use something like `/path`.

This place may need to be optimized https://github.com/getkin/kin-openapi/blob/v0.74.0/routers/gorillamux/router.go#L38

---

Additional:

If I don't want to verify the host now, I can change

```yaml
servers:
- url: /abc
``` 
to
```yaml
servers:
- url: http:///abc
```

But if I want to not check scheme, there seems to be no way now?

**Comment by fenollp** [comment]
Indeed, from https://github.com/OAI/OpenAPI-Specification/blob/d9ac75b00c8bf405c2c90cfa9f20370564371dec/versions/3.0.0.md#fixed-fields-4
```
REQUIRED. A URL to the target host. This URL supports Server Variables and MAY be relative, to indicate that the host location is relative to the location where the OpenAPI document is being served. Variable substitutions will be made when a variable is named in {brackets}.
```
(let's quote the actual docs shall we)
I guess to handle relative URLs we need a way to know where the document is being served and resolve to an absolute URL from here.

**Comment by uk-taniyama** [comment]
`
If the server URL is relative, it is resolved against the server where the given OpenAPI definition file is hosted.
`

so relative URL is valid. 
but relative URL cannot be used for schema validation.

If verification is required, I think it is necessary to set from the top.

**Comment by adyatlov** [comment]
Hi @fenollp, please consider my fix: https://github.com/getkin/kin-openapi/pull/450
