### ISSUE TITLE
invalid components: unsupported 'format' value "uuid"

### ISSUE THREAD

**Issue by febytanzil** [getkin/kin-openapi#442]
Hi, I got this error when I tried to call Validate: invalid components: unsupported 'format' value "uuid"

```
swagger, err := openapi3.NewLoader().LoadFromData(bytes)
if err := swagger.Validate(ctx); err != nil {
  log.Println(err)
}
```

but based on https://swagger.io/specification/#data-types
it states that 
> Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification.
> Tools that do not recognize a specific format MAY default back to the type alone, as if the format is not specified
and I believe, the Validate func should bypass the format "uuid" validation.

Would this be possible to allow uuid and other unspecified formats?

Thanks.

**Comment by fenollp** [comment]
https://pkg.go.dev/github.com/getkin/kin-openapi@v0.80.0/openapi3#SchemaFormatValidationDisabled
