### ISSUE TITLE
Recursive definitions cause infinite looping

### ISSUE THREAD

**Issue by chrisdostert** [getkin/kin-openapi#447]
If you attempt to generate models for a schema like below, it results in an infinite loop that never completes.

This was originally mentioned in https://github.com/getkin/kin-openapi/issues/309. 

```yaml
openapi: 3.0.1
info:
  title: Recursive refs example
  version: "1.0"
paths: {}
components:
  schemas:
    Complex:
      type: object
      properties:
        parent:
          $ref: '#/components/schemas/Complex'
```

**Comment by fenollp** [comment]
Hi Chris do you mind telling us a bit more about how to produce the bug? 
Loading seems fine: https://github.com/getkin/kin-openapi/pull/448

**Comment by nguyer** [comment]
I think I may have run into this same issue. I have a Go struct that looks like this:

```go
type FFIParam struct {
	Name         string      `json:"name"`
	InternalType string      `json:"internalType"`
	Type         string      `json:"type"`
	Components   []*FFIParam `json:"components,omitempty"`
}
```

And when trying to generate the openapi spec for it, it appears that it goes into an infinite loop and overflows the stack. I've attached the relevant snippet of the log from where this happens. Happy to provide more detail on the code that's generating the openapi if needed.

[log.txt](https://github.com/getkin/kin-openapi/files/7589665/log.txt)

**Comment by peterbroadhurst** [comment]
Created the following UT in `openapi3gen` to reproduce the issue, and work on a fix:

```go
func TestRecursiveSchema(t *testing.T) {

	type RecursiveType struct {
		Field1     string           `json:"field1"`
		Field2     string           `json:"field2"`
		Field3     string           `json:"field3"`
		Components []*RecursiveType `json:"children,omitempty"`
	}

	schemaRef, _, err := NewSchemaRefForValue(&RecursiveType{})
	require.NoError(t, err)

	_, err = schemaRef.MarshalJSON() // *** this blows the stack ***
	require.NoError(t, err)

}
```

**Comment by fenollp** [comment]
@chrisdostert Hi! Are you able to produce a code sample that reproduces your issue?

I think the Kaleido people are experiencing a different issue, from the little code you shared...
