### ISSUE TITLE
Preserving order of parsed OpenAPI?

### ISSUE THREAD

**Issue by rlabrecque** [getkin/kin-openapi#47]
Hey, I'm trying to parse an OpenAPI yaml/json file into a different format, I've got everything set up and it works great -- except the non-determinism with go's map. I'm not too familiar with go or OpenAPI yet but is there a better way of accomplishing this other than replacing basically every map in the library with an ordered map?

If I have a yaml file that looks like this:
```
openapi: 3.0.0
components:
  schemas:
    A:
      type: "object"
    B:
      type: "object"
      properties:
        a:
          $ref: '#/components/schemas/A'
```

I want to loop through all schemas, and ALWAYS get A then B.

Currently I'm looping like the validate methods do:

```
for k, v := range components.Schemas {
}
```

**Comment by fenollp** [comment]
If you only require determinism you can sort the keys of the map before going through it.

**Comment by rlabrecque** [comment]
I think I actually need more than that, for example this case:

```
openapi: 3.0.0
components:
  schemas:
    B:
      type: "object"
    A:
      type: "object"
      properties:
        someProperty:
           type: "boolean"
        b:
          $ref: '#/components/schemas/B'
```

Generating to a language like C++:

```
struct B {};

struct A {
    A::A(bool _someProperty, B _b) {
        someProperty = _someProperty;
        b = _b;
    }

    bool someProperty;
    B b;
};
```
B needs to come before A so that A knows about B. And then the properties also get randomized which is actually worse. I don't particularly want to create a dependency graph when I can do it manually.

I tried modifying kin-openapi to use one of these:

https://github.com/iancoleman/orderedmap
https://github.com/cevaris/ordered_map
https://github.com/emirpasic/gods#linkedhashmap

But I wasn't super successful mostly just because none of them implement the same API as go's built in map which I understand is a language limitation, combined with my limited knowledge of Go. This may be a place where #37 could help?

In the meantime I've moved on to https://github.com/Microsoft/OpenAPI.NET unfortunately as it defaults to an ordered map which is more important to me than using Go.

I'm curious what swagger itself does for things like `path`'s because that was always consistent for us, I'm not sure if it's consistent from the definition order or just sorted after loading though.

Let me know if you need anything else from me, I'm going to leave this issue open just because I strongly feel that it should be something this library should eventually end up supporting, but feel free to close it if you disagree.

**Comment by fenollp** [comment]
Here A depends on B. How do you plan on supporting recursive / circular dependencies?
I think you need to build that graph as an ordered map won't handle that case IMO.

**Comment by rlabrecque** [comment]
We just don't do/allow recursion/circular dependencies in our openapi because it's not really supported in our targets, I wonder how https://github.com/swagger-api/swagger-codegen solves it. (It was deterministic based on the openapi definition order from what I could tell, that was what I used first before trying out kin-openapi.)

**Comment by fenollp** [comment]
I wonder: are you not able to do something akin to:
```cpp
struct A;
struct B;

struct A {
    A::A(bool _someProperty, B _b) {
        someProperty = _someProperty;
        b = _b;
    }

    bool someProperty;
    B b;
};

struct B {};
```

My C++ is a bit rusty but I think one can declare classes before defining them properly.

Anyway I'm not willing to put in the work to use ordered maps myself. If someone were to submit a PR I'll review it.

**Comment by axpira** [comment]
Have any solution for this?

Because I want to know the properties of schema in same order of declared, Is it possible?

For example:
```
openapi: 3.0.0
components:
  schemas:
    Test:
      type: object
      properties:
        id: 
          type: integer
        date:
          type: string
```



But when I print the properties it show date before id.
I need to identify that id is before the date in definition

**Comment by fenollp** [comment]
Again, written order of map keys is discarded as a map’s key ordering has no meaning.

**Comment by fenollp** [comment]
This should help https://github.com/getkin/kin-openapi/pull/121#issuecomment-537439263

**Comment by rlabrecque** [comment]
Nice, thanks for the update!
