### ISSUE TITLE
Getting unsupported content type for xml file

### ISSUE THREAD

**Issue by metinogurlu** [getkin/kin-openapi#473]
I am trying to create an upload endpoint which accepts xml file. But I am getting `unsupported content type` error because there is no body decoder for text/xml in the code. But when I try to change contet type I am getting `header Content-Type has unexpected value` error in this time. After disabling kin validator everyting working proparly but what should I do to use it?

I just want to accept xml file.

This is my openapi spec

```
/api/v1/srv/upload/kbl:
    post:
      tags:
        - srv
      summary: Upload xml file to process it.
      operationId: upload.file
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
            encoding:
              file:
                contentType: text/xml
```

**Comment by nsp** [comment]
Have you tried using the `openapi3filter.RegisterBodyDecoder`? There is an example usage of it [here](https://github.com/getkin/kin-openapi#custom-content-type-for-body-of-http-requestresponse)

**Comment by metinogurlu** [comment]
Okay I fixed that problem like 

```
func xmlBodyDecoder(body io.Reader, h http.Header, schema *openapi3.SchemaRef, encFn openapi3filter.EncodingFn) (decoded interface{}, err error) {
	var data []byte
	if data, err = ioutil.ReadAll(body); err != nil {
		return
	}

	return string(data), nil
}
```

```openapi3filter.RegisterBodyDecoder("text/xml", xmlBodyDecoder)```
