### ISSUE TITLE
Validation does not spot response header bug

### ISSUE THREAD

**Issue by peteole** [getkin/kin-openapi#480]
Hi,
I have the following issue:

I have an OpenAPI 3 schema which has a bug in an operation on a path.
The response headers do not contain a datatype, which is wrong, but not spotted. For example:

``` yaml
...
paths:
  /example/path:
    post:
      description:Example Description
      operationId: example id
      responses:
        '200':
          content:
            audio/wav:
              schema:
                $ref: '#/example-ref'
          description: Example description
          headers:
            X-Example-Header:
              description: example description
...
```
When I call validate on the whole schema, this is not spotter, however it is wrong as visible in the swagger editor.

**Comment by peteole** [comment]
I think the issue is here:
https://github.com/getkin/kin-openapi/blob/a99f24ae4cc10440e722c2eacc4282956663c79b/openapi3/response.go#L98
The Description and Content fields are checked for validity, but the Headers and Links are not.

**Comment by fenollp** [comment]
[You are indeed correct](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#:~:text=For%20more%20complex,for%20the%20parameter.) and https://editor.swagger.io/ reports the following message
> should have either a `schema` or `content` property

---

> The Description and Content fields are checked for validity, but the Headers and Links are not.

Correct again!

These are two bugs that need solving. If you don't mind opening a PR I'd be happy to review it.

**Comment by peteole** [comment]
Here's the PR:
https://github.com/getkin/kin-openapi/pull/505
