### ISSUE TITLE
Vaildate minimum, maximum, maxLength, minLength, minItems, maxItems type constraints

### ISSUE THREAD

**Issue by mariaefi29** [getkin/kin-openapi#484]
Dear developers,

Thank you very much for a great package! Really good work!

I have noticed that this package doesn't validate the constraints of data types, such as:

1. minimum, maximum for integers
2. maxLength, minLength for strings
3. minItems, maxItems for arrays

More informations about this: https://swagger.io/docs/specification/data-models/data-types/

Has it been done on purpose or are you planning to add that feature later down the road?

**Comment by crodwell** [comment]
You should post a failing test example. It does validate those things for me.

**Comment by mariaefi29** [comment]
I apologise, I had tested on a boundary number before :(

yes, it works! Thank you! Closing the issue.
