### ISSUE TITLE
Extra parameters invalidation

### ISSUE THREAD

**Issue by mockthebear** [getkin/kin-openapi#488]
Hello, I'm not sure if this issue have been opened in the past... And probably its a feature request

The thing is, given an object validation in the body (JSON), or a query string has parameters that were undefined by the .json the request just pass trought

```json
"properties": {
          "name": {
            "type": "string"
          },
          "id": {
            "type": "int"
          }
}
```

Payload:
```
{"name": "bear", "id": 1337, "data": "some extra stuff", "test": [1,2,3,4,5,6]}
```

The same for query string, having just "page" and "limit" as the only defined parameters, sending a request with extra parameters makes the request also pass:
`/v1/endpoint?page=1&limit=123&data=1223&teste=testing`

Is there a way already to define the behavior to be strict with the parameters defined? 
This should be true for any kind of formData, query string and object passed trought JSON (maybe xml?)

**Comment by fenollp** [comment]
FYI https://json-schema.org/understanding-json-schema/reference/object.html#:~:text=Setting%20the%20additionalProperties%20schema%20to%20false%20means%20no%20additional%20properties%20will%20be%20allowed.

**Comment by shubhamkr-cohesity** [comment]
Is there any resolution here?
