### ISSUE TITLE
Parsing error when validating certain external ref 

### ISSUE THREAD

**Issue by aberhallo** [getkin/kin-openapi#495]
Similar to [issue-180](https://github.com/getkin/kin-openapi/issues/180 ) we get an error when using external refs: 

_expected fragment prefix '#/' in URI "#"_

But in contrast to issue-180 the schema http://schemas.sentex.io/store/categories.json works without any problem. We get this problem when use the schema  http://json-schema.org/draft-04/schema.

Unfortunately we don't get any more detail why it fails with this scheme. 

Any help appreciated. 

Regards
Andreas

**Comment by fenollp** [comment]
Thanks for digging through issues looking for duplicates. This is greatly appreciated!
Please provide minimalized Go code that reproduces your issue.

**Comment by aberhallo** [comment]
Hi, thanks for quick reply. You can use the following code:

```
import (
	"github.com/getkin/kin-openapi/openapi3"
	"testing"
)

func TestReadSwaggerErr(t *testing.T) {
	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	_, err := loader.LoadFromFile("./openApi3.yaml")
	if err != nil {
		t.Error(err)
	}
}
```

The OpenAPI spec is the same as issue-180 with an adopted url:
    
```
  openapi: 3.0.1
  servers:
    - url: 'http://localhost:5000'
  info:
    version: v1
    title: Products api
    contact:
      name: me
      email: me@github.com
    description: This is a sample
  
  paths:
    /categories:
      get:
        summary: Provides the available categories for the store
        operationId: list-categories
        responses:
          '200':
            description: this is a desc
            content:
              application/json:
                schema:
                  $ref: http://json-schema.org/draft-04/schema
  ```
