### ISSUE TITLE
versus swaggo and swagger?

### ISSUE THREAD

**Issue by KantarBruceAdams** [getkin/kin-openapi#51]
What is the motivation for creating this project for openAPI 3.0 rather than extending either swaggo or swagger to include it?

It would be helpful to newcomers to explain this on the front page.

**Comment by fenollp** [comment]
There is this open issue https://github.com/go-openapi/spec/issues/21
I have commit rights on both projects & welcome initiative and contributions :)

**Comment by KantarBruceAdams** [comment]
interesting conversation there but I'm none the wiser.

**Comment by fenollp** [comment]
I hope this helps :)
