### ISSUE TITLE
Examples in the README.md are not very helpful. 

### ISSUE THREAD

**Issue by dwjohnston** [getkin/kin-openapi#536]
For context, I'm someone who doesn't have any experience with Go or API frameworks for Go such as gorilla/mux. I do have plenty experience with creating APIs with Node.js. 

As far as I can tell - the examples in the main readme do not reflect a practical application of the tooling. 

I've taken the [second example](https://github.com/getkin/kin-openapi#validating-http-requestsresponses) (Validating HTTP Request/Responses) pasted it into a main.go and pasted in an example OpenAPI file that fits: 

```
#openapi3_spec.yaml
openapi: 3.1.0
info:
  title: Demo
  description: |
    demo demo demo
  version: 1.0.0

paths:
  /items:
    get:
      summary: demo
      operationId: get-items
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
```

When we run this, we don't get any errors - but we don't get a running server either - the code just executes and exits. 

Repro of this [here](https://github.com/dwjohnston/open-api-play/tree/999f95d2e1081960c900ca82230a1adbaeeeef71) 

Instructions 
 - Check out the code
 - `cd api-go`
 - `go get ./... && go run main2.go`
  

It would be a whole more helpful if you can provide examples how how this should fit in with use of gorilla/mux - if that's the intended tooling.

**Comment by fenollp** [comment]
Ah well, this example does not provide a server and isn't quite copy-pastable.
Have a look at the documentation on pkg.go.dev, specifically: https://pkg.go.dev/github.com/getkin/kin-openapi@v0.94.0/routers/gorillamux#example-package

I'll amend the README a bit and close this.

**Comment by dwjohnston** [comment]
@fenollp  If you're interested I've got a sample of the current best direction I'm thinking of here: 

https://github.com/dwjohnston/openv3-test/blob/8bdde818fee0bb31f7994813e75263ffcce6a397/api-go/server.go#L106


Which is that after validating the request, you now enter a switch statement type logic, to actually handle the request and determine the response. 

```
func handleRequest(router routers.Router, httpReq *http.Request) {

	route, pathParams, err := router.FindRoute(httpReq)

	path := route.Path
	method := route.Method

	if path == "/users" && method == "POST" {
		return // return the things here 
	}

	if path == "/users" && pathParams["username"] != "" && httpReq.Method == "GET" {
		return
	}

	if path == "/users" && httpReq.Method == "GET" {
		return
	}

}
```

You then validate the response and return a 500 if it's incorrect. 

But this seems a little off - I feel like you've built a more elegant solution in with that mux wrapper.
