### ISSUE TITLE
Response validation: validate headers

### ISSUE THREAD

**Issue by jamietanna** [getkin/kin-openapi#546]
I've noticed while using the response validation filter for OpenAPI 3.x that header validation isn't performed.

As they can be marked as `required` we should validate them too.

**Comment by fenollp** [comment]
Closing as duplicate of https://github.com/getkin/kin-openapi/issues/201
Please try implementing this, I'll happily review your code :)

**Comment by fenollp** [comment]
@jamietanna see https://github.com/getkin/kin-openapi/pull/650
