### ISSUE TITLE
SchemaRef marshaller prefers ref over value

### ISSUE THREAD

**Issue by john-dev** [getkin/kin-openapi#568]
Is there a way to marshal a value over a ref when it comes to marshalling the SchemaRef?
I need a json output that resolved all internal $ref's and i try to avoid iterating recursivly.

Am i missing something?

**Comment by nktch1** [comment]
Hi! I ran into a similar problem, any updates on the topic? Is the PR ready?

**Comment by john-dev** [comment]
> Hi! I ran into a similar problem, any updates on the topic? Is the PR ready?

Not from my site. I will close this Ticket - maybe the developers are down to change this in https://github.com/getkin/kin-openapi/pull/569
