### ISSUE TITLE
Fails to validate openApi spec for regex pattern

### ISSUE THREAD

**Issue by SuperMohit** [getkin/kin-openapi#574]
` "pattern": "^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)(\\.(?!$)|$)){4}|([0-9a-f]{1,4}\\:){7}[0-9a-f]{1,4}$"`

I am trying to validate an openApi spec with the above property. It fails if I call validate function.
But same regex seems to be valid on https://regex101.com/

```
	err = doc.Validate(context.Background())
	if err != nil {
		log.Fatalf("%v", err)
	} 
```

**Comment by fenollp** [comment]
Not all regexp engines are the same...

What's the output you're getting and what other thing did you expect?
Please share code as a regression test. It's easier for everyone.

**Comment by SuperMohit** [comment]
yeah I understand all regexp engines are not same. 

I am trying to parser [https://www.mongodb.com/docs/atlas/reference/api-resources-spec/](swagger)  with the code below but patterns are throwing error: 

doc, err := openapi3.NewLoader().LoadFromFile("gen/swagger.json")
	if err != nil {
		fmt.Printf("%v", err)
		os.Exit(1)
	}
	// validate the swagger.yaml matches Openapi spec
	err = doc.Validate(context.Background())
	if err != nil {
		log.Fatalf("%v", err)
	}



```
2022/07/29 11:48:21 invalid components: cannot compile pattern "^([a-zA-Z0-9]([a-zA-Z0-9-]){0,21}(?<!-)([\\w]{0,42}))$": error parsing regexp: invalid or unsupported Perl syntax: `(?<`
Schema:
  {
    "description": "Human-readable label that identifies the cluster containing the snapshots you want to retrieve.",
    "maxLength": 64,
    "minLength": 1,
    "pattern": "^([a-zA-Z0-9]([a-zA-Z0-9-]){0,21}(?\u003c!-)([\\w]{0,42}))$",
    "readOnly": true,
    "type": "string"
  }
```

**Comment by TristanSpeakEasy** [comment]
@SuperMohit https://github.com/getkin/kin-openapi/pull/590 was merged recently which allows you to disable pattern validation, does that suit your needs here? Or are you looking to validate these patterns?

**Comment by fenollp** [comment]
The validation flag should solve your issue. If that's not the case please reopen.
