### ISSUE TITLE
Examples not being validated

### ISSUE THREAD

**Issue by danicc097** [getkin/kin-openapi#588]
As per #526 I'd expect schema `examples` to be validated as well, but I can't get these tests to fail validation using either `examples` or `example` (this one not implemented afaik). Am I missing something in the code below?

```go
package openapi3

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestExamplesValidation(t *testing.T) {
	spec := []byte(`
openapi: 3.0.0

paths:
  /user:
    post:
      description: User creation.
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
            examples:
              BadUser:
                $ref: '#/components/examples/BadUser'
        description: Created user object
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateUserResponse"
          description: successful operation
      # security:
      #   - api_key: []
      summary: creates a new user
      tags:
        - user
components:
  schemas:
    CreateUserRequest:
      description: represents a new User
      example:
        username: "]bad["
        email: bad
        password: short
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          pattern: "^[ a-zA-Z0-9_-]+$"
          minLength: 3
        email:
          type: string
          pattern: "^[A-Za-z0-9+_.-]+@(.+)$"
        password:
          type: string
          minLength: 7
      title: a User
      type: object
    CreateUserResponse:
      description: represents the response to a User creation
      properties:
        access_token:
          type: string
        user_id:
          format: int64
          type: integer
      type: object
# implemented in #526
  examples:
    BadUser:
      value:
        username: "]bad["
        email: bad
        password: short
info:
  title: An API
  version: 1.2.3.4
`)

	loader := NewLoader()

	doc, err := loader.LoadFromData(spec)
	require.NoError(t, err)

	err = doc.Validate(loader.Context)
	require.Error(t, err) // FAIL
}
```

**EDIT**: well this explains it:

```go
// Validate returns an error if Example does not comply with the OpenAPI spec.
func (example *Example) Validate(ctx context.Context) error {
	return nil // TODO
}
```

Is this being worked on/planned/would accept a PR for it?

**Comment by fenollp** [comment]
Hi! Thanks for taking the time to produce a runnable test!! You could even have opened a PR with it to show the results from the CI build but that's alright.

Indeed as you've noted `Example` validation is not implemented yet. Feel free to open a PR, I'll happilly review and merge it!
You'll probably need this: https://github.com/getkin/kin-openapi/blob/5a61040f9c83432717fde755d16649eca5e21038/openapi3/schema_test.go#L1026

WRT `example`: I don't see it as being part of the OpenAPIv3 spec. I only find `examples`: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#exampleObject

**Comment by danicc097** [comment]
Regarding `examples` and `example`, I was using this as reference: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#mediaTypeObject.
I'll update the spec in the tests, but I see it's defined in 3.0.0 as well

Based on that, a schema definition can have a `example`, and we can also specify either `example` or `examples` in media types (which can reference `components/examples`). I was thinking of something like https://github.com/getkin/kin-openapi/blob/5a61040f9c83432717fde755d16649eca5e21038/openapi3filter/validate_request.go#L31

but inputs would just be an example's `value` and a `SchemaRef` so we can validate examples both in schemas and media types.
