### ISSUE TITLE
Existing valid specs now fail validation because of circular reference check.

### ISSUE THREAD

**Issue by sorintm** [getkin/kin-openapi#615]
Existing specs which used to validate fine with previous version, are now failing to load because of the new circular reference check [https://github.com/getkin/kin-openapi/pull/607].
The hardcoded limit of 3 visits per definition is too aggressive for complex API specs.
I propose increasing the default check limit to a higher number like 100 or 1K. Since the check was introduced to guard against infinite loop, a higher limit would still do the job, but would allow for complex specs to still be validated correctly.
Ideally the limit should be configurable on the loader.

**Comment by fenollp** [comment]
Hey thanks for the quick reporting and sorry about that.

Could you share one of these documents please?

I'm thinking this number should be a `var CircularReferenceCounter = 3`. Or would a `Loader` field be preferable?
cc @TristanSpeakEasy as they may have an opinion on this.

**Comment by TristanSpeakEasy** [comment]
@sorintm do you have examples of specs that used to validate but now don't because of this? Would be great to see some of these complex specs.

@fenollp I think a public var is probably fine, I don't think it is likely a setting that would need to be changed per instance, likely just per integration

**Comment by sorintm** [comment]
Thanks for the quick turnaround!
Unfortunately I cannot share the full spec, but I have extracted the minimum bits that trigger the circular ref validation.
I have opened this PR with a test that reproduces the issue: [616](https://github.com/getkin/kin-openapi/pull/616).
The PR is meant to help with the repro and the test case is very specific. Feel free to reject it.
