### ISSUE TITLE
Validating and unmarshaling structs from schema

### ISSUE THREAD

**Issue by juandiegopalomino** [getkin/kin-openapi#621]
Hi there! So this is a really cool project and I have an odd use case I was wondering this could cover: I would like to use this to both validate and unmarshal a config file passed in by a user in a CLI app. Basically I would have the schema yaml at hand and on the start of the program it would load up the user provided config data as `[]byte` and then 1) validate the input against the given schema 2) load the data into a struct (including filling in expected defaults from the schema). If anyone can provide some guidance/examples of this I would greatly appreciate it!

**Comment by fenollp** [comment]
Hi! Sounds like you're looking to validate data against a schema, nothing specific to HTTP APIs. 
I suggest you take a look at libraries such as https://github.com/xeipuuv/gojsonschema
