### ISSUE TITLE
question: how to get fake request body from schema

### ISSUE THREAD

**Issue by samhair** [getkin/kin-openapi#668]
Hi team,

It's my question here, please free to close it if it's not OK to file a issue.
Here is the thing, after parse from a openapi doc, we can get schema of request body, like:
{
  "properties":
    {
      "email":
        {"type":"string"},
      "password":
        {"type":"string"},
      "username":
        {"type":"string"}
    },
  "type":"object"
}
Is it possible to get the following fake json?
{
  "email": "string",
  "password": "string",
  "username": "string"
}

BR
Sam

**Comment by fenollp** [comment]
Did you take a look at how ReDoc does it?
