### ISSUE TITLE
Support for keyword "explode" in an operation's parameter

### ISSUE THREAD

**Issue by nikolaas** [getkin/kin-openapi#68]
Hello.

According to the OpenAPI 3 specification an operation's parameter can contain keyword "explode" (see sections [Describing parameters](https://swagger.io/docs/specification/describing-parameters/) and [Parameter serialization](https://swagger.io/docs/specification/serialization/)).

Do you plan to add support for the keyword?

**Comment by fenollp** [comment]
I guess the plan here is to support the whole of OpenAPI `v3.*.*`. Things get implemented on a per-need basis. PRs welcomed! :)

**Comment by fenollp** [comment]
Fixed by https://github.com/getkin/kin-openapi/pull/72
