### ISSUE TITLE
readOnly validation causing backwards incompatibility

### ISSUE THREAD

**Issue by simonjpartridge** [getkin/kin-openapi#689]
The addition of validation for readOnly https://github.com/getkin/kin-openapi/pull/599 has caused issues for our existing clients when calling our API.

Especially in the flow where a user does a put update, they end up incidentally sending readOnly parameters to the API.

```
x = GetX
x.Value = "updated"
UpdateX(x)
```

Ideally I think the readOnly validation should be optional with a configuration option.

Would you be open to this change if we were to raise a PR to implement it?

**Comment by fenollp** [comment]
Sure! Send away :)

**Comment by gczobel** [comment]
It's someone working right now on this? @simonjpartridge  I can take this if you are not actively working on it.

**Comment by orshlom** [comment]
Hey @fenollp, please review the PR when you got the time 😏 

I have made `writeOnly` properties validation configurable as well.
