### ISSUE TITLE
Support for full validation of operation's parameters

### ISSUE THREAD

**Issue by nikolaas** [getkin/kin-openapi#69]
Hello.

At the moment package `github.com/getkin/kin-openapi/openapi3filter` support validation of parameters with type `string` only.

Do you plan to add support for validation of parameters with other types?

P.S. I can help with it if you don't mind.

**Comment by fenollp** [comment]
I know I'm interested. I'll review any PR you throw at me :)

**Comment by fenollp** [comment]
Fixed by https://github.com/getkin/kin-openapi/pull/76
