### ISSUE TITLE
RegisterBodyDecoder for text/csv

### ISSUE THREAD

**Issue by cosma** [getkin/kin-openapi#696]
Hello, I implemented your library and I have when I upload a csv file.  error in openapi3filter.RequestError: request body has an error: failed to decode request body: path file: unsupported content type \"text/csv\"

Could you also please register a body  decoder for CSV files  `RegisterBodyDecoder("text/csv", csvBodyDecoder)`

https://github.com/getkin/kin-openapi/blob/871801135891449a4ba33576e883232fc513069a/openapi3filter/req_resp_decoder.go#L999-L1008

Any help is super appreciated!
Thanks in advanced and this is quite urgent.

**Comment by fenollp** [comment]
Here's a starting point: https://pkg.go.dev/encoding/csv

If someone finds a way to write an enc/dec/oder for text/csv that does not bring non-std dependencies I'll probably merge this.

I might get around to it but it's /not high/ on my list.

**Comment by fenollp** [comment]
This should be a simple enough starting point: https://github.com/getkin/kin-openapi/pull/730
