### ISSUE TITLE
How do I flatten a document?

### ISSUE THREAD

**Issue by KarmanyaOberoi1997** [getkin/kin-openapi#713]
Is it possible to resolve or dereference $ref in component schemas or resolve an openapi spec fully using this implementation? I am looking for something similar to what is offered by the java resolveFully functionality in openapi parser.

**Comment by fenollp** [comment]
Context: https://github.com/swagger-api/swagger-parser/tree/c0c434bf1c0189e9a770e31c50d4bc19bcf2dd08#2-resolvefully

So I think you're looking for the dual of "flatten" (which is https://pkg.go.dev/github.com/getkin/kin-openapi/openapi3#T.InternalizeRefs ) but this is not implemented in this lib.

I welcome PRs though. This should be easier to implement than InternalizeRefs and one can use https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/ResolverFully.java as a guide.

**Comment by fenollp** [comment]
Actually https://github.com/getkin/kin-openapi/issues/98
