### ISSUE TITLE
any optiont to treat path with and without trailing slash the same?

### ISSUE THREAD

**Issue by tigerinus** [getkin/kin-openapi#739]
I find that request validator differentiate these two specs: one with trailing slash (e.g. `GET /event/?a=123`) and one without (e.g. `GET /event?a=123`). To workaround it I will have to define both.

```yaml
  /event/:
    get:
      summary: Get all events
      responses:
          ...
```

```yaml
  /event:
    get:
      summary: Get all events
      responses:
          ...
```

Is there an option so both `GET /event/?a=123` and `GET /event?a=123` are mapped to the same route?

Thanks!

**Comment by fenollp** [comment]
There's no such option. These are semantically different routes, how do you see such an option should work?
