### ISSUE TITLE
Loader fails to load file with no reason

### ISSUE THREAD

**Issue by akzincsystems** [getkin/kin-openapi#759]
I'm seeing an error:

`bad data in "#/components/schemas/UserStruct"`

when calling `openapi3.NewLoader().LoadFromFile(path)`

This is being emitted from `openapi3/loader.go` L358 which is the default case in a switch statement, and no reason is given.

Dumping the reflect values gives:
reflect.TypeOf(cursor).Kind().String == ptr
reflect.TypeOf(cursor).String() == *openapi3.SchemaRef

which I can see for all other schema components as well

The particular component is:
```
  schemas:
    UserStruct:
      title: "A User"
      type: object
      properties:
        struct:
          $ref: "#/components/schemas/StructVersionV1"
        data:
          $ref: "#/components/schemas/UserV1"
```
All referenced schemas are in the file and the entire yaml schema validates at https://app.swaggerhub.com

lib version is: github.com/getkin/kin-openapi v0.113.0

Any ideas why this might be happening?

**Comment by fenollp** [comment]
Hello! Can you provide a YML that reproduces the error with a call such as
```
go run github.com/getkin/kin-openapi/cmd/validate@latest -- file.yml
```

**Comment by akzincsystems** [comment]
[example.zip](https://github.com/getkin/kin-openapi/files/10557586/example.zip)

I'd appreciate you deleting it once you have it locally.

Thanks

**Comment by akzincsystems** [comment]
Not seeing this yet. Needs a new tag?

**Comment by akzincsystems** [comment]
Ah Ha!  Found it - yes - correct. Thanks for that. Hopefully your new messaging will point the error at the wrong ref, not the ref definition itself.  Look forward to seeing it. Thanks for your help.
