### ISSUE TITLE
"Required" validation does not work correctly with a request's body

### ISSUE THREAD

**Issue by nikolaas** [getkin/kin-openapi#77]
Hello!

There is an operation in my OpenAPI specification that contains a required body. I call `openapi3filter.ValidateRequest` with HTTP request that does not contains a body. I expect that the function will return an error but it returns `nil`.

## Steps to Reproduce the Problem (including complete and simple design if relevant)

```go
package main

import (
	"fmt"
	"net/http"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3filter"
)

func main() {
	requestBody := openapi3.NewRequestBody().
		WithRequired(true).
		WithJSONSchema(openapi3.NewStringSchema())
	operation := openapi3.NewOperation()
	operation.OperationID = "test"
	operation.RequestBody = &openapi3.RequestBodyRef{Value: requestBody}
	spec.AddOperation("/test", http.MethodPost, operation)

	router := openapi3filter.NewRouter()
	if err := router.AddSwagger(spec); err != nil {
		return nil, err
	}
	
	req, err := http.NewRequest(http.Method, "/test", nil)
	if err != nil {
		return nil, err
	}
	
	route, pathParams, err := router.FindRoute(req.Method, req.URL)
	if err != nil {
		return
	}
	
	input := &openapi3filter.RequestValidationInput{Request: req, PathParams: pathParams, Route: route}
	if err := openapi3filter.ValidateRequest(req.Context(), input); err != nil {
		fmt.Printf("error %[1]T: %s\n", err)
		return
	}
	fmt.Println("no error")
}
```

## Actual Behavior

Function `openapi3filter.ValidateRequest` returns `nil`.

## Expected Behavior

Function `openapi3filter.ValidateRequest` returns `*openapi3filter.RequestError`.

## Specifications

kin-openapi version: commit [9acc5e9](https://github.com/getkin/kin-openapi/commit/9acc5e936becff2d656c4551e6c471d945809678).

**Comment by fenollp** [comment]
Fixed by https://github.com/getkin/kin-openapi/pull/78
