### ISSUE TITLE
remove gorilla/mux

### ISSUE THREAD

**Issue by jxsl13** [getkin/kin-openapi#777]
gorilla/mux is a pretty big dependency that is not maintained (anymore) nor used extensively by this library.

Imo it would be great if it was removed.
The scope of this library seems to be more the parsing of openapi specifications. Router wrappers or convenience functions should be externalized.

**Comment by fenollp** [comment]
Oh wow I did not notice gorilla/mux got archived.

I agree with you. The `routers` package and subpackages should move to another repo under this organization.
I'll contact the org owner to create the repo.

**Comment by jamietanna** [comment]
Gorilla Toolkit is now unarchived 👏 https://gorilla.github.io/blog/2023-07-17-project-status-update/

**Comment by jxsl13** [comment]
it's sadly still a big dependency.

**Comment by jamietanna** [comment]
Big dependency in what way? There's no transitive dependencies pulled in as part of this ([gorilla/mux `go.mod`](https://github.com/gorilla/mux/blob/main/go.mod)).

Go Modules will trim the module dependency graph, so if you're not using a package from `kin-openapi` that uses `gorilla/mux`, Go won't download it, so it shouldn't cause any issues

**Comment by jxsl13** [comment]
I see, it is indeed very small. I thought it was a big dependency but taking a second glance at the repo it's just a few go files for the mux.
