### ISSUE TITLE
The schemaref ref field does not work

### ISSUE THREAD

**Issue by Chise1** [getkin/kin-openapi#784]
When i try to assemble a openapi.T(don't use loader),and use SchemaRef like:
`go

openapi3.SchemaRef{Ref:"xxx"}

`
I got an error: schemaRef's value can not be  none(When I try to use validate func).

How can i do it?

**Comment by Chise1** [comment]
The real problem is that instead of using ref, you use value when you output the document

**Comment by fenollp** [comment]
You're mistaken, it's the other way around: https://github.com/getkin/kin-openapi/blob/d12c756ae00eff9f6a0a30aba254014bbf667905/openapi3/refs.go#L24

If you want to serialize the value, simply unset the ref.

If you feel this is not well documented, please share your research workflow. Thanks!
