### ISSUE TITLE
OAS3: Support for custom formats like `email`, `uuid`, etc for `string` properties?

### ISSUE THREAD

**Issue by dsolonenko** [getkin/kin-openapi#79]
Hello,

From OAS3 spec:
>  Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification.

I was wondering if the validation can be extended to support some reasonably common formats like `email`, `uuid`?

**Comment by fenollp** [comment]
https://godoc.org/github.com/getkin/kin-openapi/openapi3#DefineStringFormat

**Comment by steffakasid** [comment]
Is it possible to configure the validation that it ignores custom defined formats (instead of defining them)?

**Comment by fenollp** [comment]
Same link, look for `SchemaFormatValidationDisabled`.
