### ISSUE TITLE
Document validation infinite loop

### ISSUE THREAD

**Issue by radwaretaltr** [getkin/kin-openapi#796]
Hi, 

We found out that in some cases, the Validate() method enters an infinite loop when validating a valid API document.

For example:
[https://github.com/APIs-guru/openapi-directory/blob/51fed63e3e6bce022cedba44ce28863bd712040c/APIs/presalytics.io/ooxml/0.1.0/openapi.yaml](url)

This happens because the "stack" slice isn't handled correctly in the validate receiver of "*Schema":
`func (schema *Schema) validate(ctx context.Context, stack []*Schema) error`

While the slice is being resliced during its lifecycle in the recursion, we do not store the resliced result and use the original slice instead. 

NOTE: In order to load this spec, we had to set the "CircularReferenceCounter" to 20.

**Comment by radwaretaltr** [comment]
Submitted a PR with the fix: #797.

**Comment by sambercovici** [comment]
@fenollp , can you please confirm the problem and assis?
