### ISSUE TITLE
Open-API Definitions 

### ISSUE THREAD

**Issue by sskserk** [getkin/kin-openapi#824]
Hi Guys,

do you have any plans to support the definitions section of the open-api specification?

**Comment by jxsl13** [comment]
please reference the section in the openapi specification which you mean.

**Comment by sskserk** [comment]
Hi @jxsl13,

Sorry, I overlooked. In OpenAPI 3.0, they all were moved inside components.  I see the "Components" in the gswagger.Options.

There is just  a question on how to put a "$ref" into the gswagger.ContentValue.Responses. I can find a way to put a reference to a component there.

Can you help please?

**Comment by fenollp** [comment]
Not sure how it works in `gswagger` but in `kin-openapi` you'd be adding a response object in `doc.Components.Responses` and your `ResponseRef` would be `ResponseRef{Ref: "#/components/responses/BLA", Value: nil}` which get properly picked up by `MarshalJSON`.

**Comment by sskserk** [comment]
@fenollp,
thank you for the note  but I'm not sure how to specify the Ref to a component.
Simply, the Definitions.Responses  is defined as "map[int]ContentValue". The ContentValue includes the Content defined as:
`type Content map[string]Schema

// Schema contains the value and if properties allow additional properties.
type Schema struct {
	Value interface{}
	AllowAdditionalProperties bool
}`  

So, there is no way to specify the  "Ref". Please correct me if I'm wrong.
