### ISSUE TITLE
Releases no longer created

### ISSUE THREAD

**Issue by marc-ste** [getkin/kin-openapi#833]
Not sure if it was intentional but GitHub releases aren't created anymore for commits to `main`. And commits to `main` are no longer tagged.

How should the latest versions of `kin-openapi` be referenced in `go.mod`?

**Comment by fenollp** [comment]
Hi Marc,
All releases appear to have a matching tag: https://github.com/getkin/kin-openapi/tags

I infer you mean to say you'd like a new release to be cut then I just did that: https://github.com/getkin/kin-openapi/releases/tag/v0.119.0
There's no release policy other than me cutting whenever it feels proper or when someone asks for it. This is holidays time in France so this has been on somewhat pause for a couple months.

In the future I encourage you to look into using `go mod edit -replace ...`
