### ISSUE TITLE
Invalid content-type incorrectly recognised as "request body error"

### ISSUE THREAD

**Issue by slonka** [getkin/kin-openapi#843]
Hi all! This is my first issue here so please be patient 🙏  (I tried searching for a similar issue but couldn't find one so I'm opening a new one).

When sending a POST request with a different content type than defined, e.g. `text-html` to:

```
paths:
  /test:
    post:
      requestBody:
        required: true
        content:
          application/json:
```

the error that is produced is `request body has an error: header Content-Type has unexpected value ""` which is not correct. This should be a parameter error. I think the problem is that `content-type`, `accept` and `authorization` are not in `parameters` list but are [treated differently](https://swagger.io/docs/specification/describing-parameters/#header-parameters).

Please let me know if my reasoning is right.

PR to show the issue: https://github.com/getkin/kin-openapi/pull/844

**Comment by fenollp** [comment]
Hi! Thanks for taking the time to raise an issue AND to bring a failing test :)

I don't see why this request body error should be a parameter error instead.

The bug I see here is `Content-Type has unexpected value ""` which should be mentioning `text/html`, not `""`. 

Wdyt?

**Comment by slonka** [comment]
Hey! 

The way I understand this is that headers are not part of the body. The HTTP request as per HTTP spec:

```
Request       = Request-Line              ; [Section 5.1](https://www.rfc-editor.org/rfc/rfc2616#section-5.1)
                        *(( general-header        ; [Section 4.5](https://www.rfc-editor.org/rfc/rfc2616#section-4.5)
                         | request-header         ; [Section 5.3](https://www.rfc-editor.org/rfc/rfc2616#section-5.3)
                         | entity-header ) CRLF)  ; [Section 7.1](https://www.rfc-editor.org/rfc/rfc2616#section-7.1)
                        CRLF
                        [ message-body ]          ; [Section 4.3](https://www.rfc-editor.org/rfc/rfc2616#section-4.3)
```

So sending a request with an unexpected header should not mention an error in the body because it's not in the body. What is more [OpenAPI docs say](https://swagger.io/docs/specification/describing-parameters/#header-parameters):

```
Note: Header parameters named Accept, Content-Type and Authorization are not allowed. To describe these headers, use the corresponding OpenAPI keywords:
```

So these headers (and other custom headers) are called parameters and that's why I think the correct type of error here should be a `RequestError` with `Parameter` that has `.Name="content-type"`, `.In="header"` and `.Required=true`.

Maybe I can check other OpenAPI validator implementations in other languages and see what error is triggered on wrong `Content-Type`.

**Comment by fenollp** [comment]
This is why this error talks about body:
```yaml
      requestBody: # <-------
        content:
          application/json
```
So receiving a body that's encoded to something not listed here is a req body issue.
Yes, that encoding is advertised through a header. The header isn't wrong, the reqbody encoding is.
Error mentions both req body and the header read: that's enough info. 

But the received header value isn't reported properly. That's the only issue here :)

**Comment by fenollp** [comment]
> But the received header value isn't reported properly. That's the only issue here :)

Ah no actually that was just a test issue. CT does get properly set: https://github.com/getkin/kin-openapi/blob/93c27569df0b4514bd92146e1158bd0be73df6a7/openapi3filter/validation_error_test.go#L142-L153
