### ISSUE TITLE
Installing Validate CMD on versions newer than v0.119.0 doesn't work

### ISSUE THREAD

**Issue by tpaulus** [getkin/kin-openapi#889]
As a result of the changes made in https://github.com/getkin/kin-openapi/commit/d14f7e054c72087d3ba0b2a75fc82bf840898cb7, it is no longer possible to install this library via `go install`

```
$ go install github.com/getkin/kin-openapi/cmd/validate@latest

go: downloading github.com/getkin/kin-openapi v0.122.0
go: github.com/getkin/kin-openapi/cmd/validate@latest (in github.com/getkin/kin-openapi@v0.122.0):
	The go.mod file for the module providing named packages contains one or
	more exclude directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Comment by fenollp** [comment]
Oh yes I have https://github.com/getkin/kin-openapi/pull/888 in the works. I still need to figure out how to make this work without exclude rules. 
I wanted to verify that the problematic yaml.v3 version was not being used. It does still appear in the go.sum but I'm not 100% sure this means dependents won't get it.
