### ISSUE TITLE
Issue validating example value when using externalValue property

### ISSUE THREAD

**Issue by mario-imperato** [getkin/kin-openapi#893]
Migrating to the latest version of the library (the version used was the v0.92.0) I stumbled into a validation error I'm not sure how to deal with.
In the examples section I have something like:

```
application/json:
  schema:
    $ref: '#/components/schemas/ErrorBaseResponse'
  examples:
    response:
      externalValue: "responseExamplesError.tmpl"
      value:
        ambit: "validation"
        message: "string"
        timestamp: "2022-03-28T12:55:03+02:00"
```

In validating the stuff I got an expected `value and externalValue are mutually exclusive`.
I removed the value property and left only the `externalValue`. I ran into an unexpected `Value is not nullable`. Apparently in the function `validateExampleValue` in `example_validation.go` gets called and determines that since the schema of the response is not nullable the value has to be there. Workaround for the error is to put `nullable: true` into the definition of the returned object.
Is that the way to deal with it or may be the validation has a problem in this specific case?
May be the error can be disabled also by options. But don't know.
Appreciate if you can shed some light on this.
Thank you
M.

**Comment by fenollp** [comment]
Hi please glance at the docs to disable that validation => https://pkg.go.dev/github.com/getkin/kin-openapi@v0.123.0/openapi3#DisableExamplesValidation

I can't help you debug your code here, please make sure to share a reproducible failing script.
