### ISSUE TITLE
Can't delete paths anymore

### ISSUE THREAD

**Issue by reuvenharrison** [getkin/kin-openapi#897]
Hi,
Before https://github.com/getkin/kin-openapi/pull/882 I could delete a path like this:
```
func filterPathsByExtensionInternal(paths *openapi3.Paths, r *regexp.Regexp) {
	for path, pathItem := range paths.Map() {
		for extension := range pathItem.Extensions {
			if r.MatchString(extension) {
				delete(paths.Map(), path)
				break
			}
		}
	}
}
```
After the PR, `Map()` returns a copy rather than the original paths map which makes it impossible to delete paths.
I suggest to add a `Delete` function in [maps.sh](https://github.com/getkin/kin-openapi/blob/master/maps.sh) similar to the `Set` function.
I'm happy to create the PR if this makes sense.

**Comment by fenollp** [comment]
Ah sorry about that. I did mean `Map()` to return a copy (in preparation of the orderedmaps PR).
You're right the solution here is as you describe.

Please send a PR :)
