### ISSUE TITLE
Stop introducing breaking changes in minor releases

### ISSUE THREAD

**Issue by maclermo** [getkin/kin-openapi#898]
Hi,

I am a user of this package. I have noticed a lot of breaking changes lately to exported function signatures. For example, out of the blue, we have to use `.Map()`...

It would be advisable to follow semantic versioning.

Cheers,
Max.

**Comment by jxsl13** [comment]
the project has not released a stable version, yet (>= 1.y.z).

**Comment by maclermo** [comment]
Hi there,

Stable has nothing to do with semver2.0.

Semver2.0 is a way for consumers of a project to know when breaking changes occur so that they are aware they need to refactor and do proper testing for regression.

The link you sent exactly explains the point I'm trying to make:

`Major version X (X.y.z | X > 0) MUST be incremented if any backward incompatible changes are introduced to the public API.`

**Comment by fenollp** [comment]
Hi @maclermo I understand you may be frustrated by the frequent changes required to upgrade usage of this lib. I try to keep them to minimum but there are required changes. 

As @jxsl13 points out this lib does follow semver. It's still v0 so ANY commit is supposedly breaking.

That being said there is probably room for improvement to the current situation. I'm open to suggestions.
Maybe I should move this changelog to a dedicated file? https://github.com/getkin/kin-openapi/tree/7d030b2b2bc170f1931e929b5401f785afe75a69#changelog-sub-v1-breaking-api-changes 
What would make more sense for you?

**Comment by maclermo** [comment]
Oh I thought the version was 1.22, not 0.122. My bad!

Then yes, we can't consider v0 as being stable.

I personally think you should start thinking about having a stable release. Having active Github issues does not make a library unstable.

Having a dedicated changelog does not fix having to refactor the code on every breaking change.

For the time being, we moved away from this lib. We are running the Swagger CLI docker image as a technical API to our business API.
