### ISSUE TITLE
Request validation doesn't support content-type wildcards

### ISSUE THREAD

**Issue by kconwayatlassian** [getkin/kin-openapi#91]
The OpenAPI documentation (https://swagger.io/docs/specification/describing-request-body/) describes the content-type keys under `requestBody.content` as supporting wildcards:

> content allows wildcard media types. For example, image/* represents all image types; \*/\* represents all types and is functionally equivalent to application/octet-stream. Specific media types have preference over wildcard media types when interpreting the spec, for example, image/png \> image/* \> \*/\* 

However, the current request validation only supports a direct match of content types via a map lookup. Additionally, the request validation rejects any request without a content-type header which should otherwise be handled by a `*/*` if defined.

My team has a specialized case where this causes validation errors because we need to support a requestor that doesn't add the content-type header. I'm happy to put up a PR that helps with this but thought I might get some feedback on the approach first:

The current lookup is handled [here](https://github.com/getkin/kin-openapi/blob/master/openapi3filter/validate_request.go#L148) with a map[string]*MediaType lookup by key. However, the `requestBody.Content` type has a `Get` method for resolving the type that also incorporates the behavior of `parseMediaType` which is used [here](https://github.com/getkin/kin-openapi/blob/master/openapi3filter/validate_request.go#L139) before the map lookup. I'm guessing the `Get` method was added after the initial implementation of the request validation and that the parsing and map lookup in the validation is a hold-over.

I believe we can hide the complexity of the lookup behavior in the [`Content.Get`](https://github.com/getkin/kin-openapi/blob/master/openapi3/content.go#L26) method. If that approach sounds acceptable then I'll get a PR up that implements the hierarchical wild-card logic.

**Comment by fenollp** [comment]
> I believe we can hide the complexity of the lookup behavior in the Content.Get  method. If that approach sounds acceptable then I'll get a PR up that implements the hierarchical wild-card logic.

Sounds correct to me. Indeed `Content` handling may have been preliminary. PRs welcomed! And thank you for your time.
