### ISSUE TITLE
bearerFormat in securitySchemes isn't validated according to spec

### ISSUE THREAD

**Issue by swiatekm** [getkin/kin-openapi#97]
This is an issue I've encountered while using ApiSprout. According to the spec, `bearerFormat` is `an arbitrary string that specifies how the bearer token is formatted` as seen here: https://swagger.io/docs/specification/authentication/bearer-authentication/.

On the other hand, it seems like `kin-openapi` only accepts `JWT` or an empty string for this field:
https://github.com/getkin/kin-openapi/blob/2557c533872b2bfc1ed92e085612f09fbce91506/openapi3/security_scheme.go#L124

I'm not much of a Go afficionado, but it seems like that whole switch statement can be removed, as we don't need to do any validation on this value.

**Comment by fenollp** [comment]
Indeed the `bearerFormat` is an arbitrary string.
> A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes.

Only the `else if` part needs to be kept here. Do you mind opening a PR please?
