### ISSUE TITLE
Please use gorilla/mux v1.8.0 instead of v1.8.1

### ISSUE THREAD

**Issue by shaofu88** [getkin/kin-openapi#988]
There is a [known bug](https://github.com/gorilla/mux/issues/751) for gorilla/mux v1.8.1. Please downgrade the version to v1.8.0.

**Comment by shaofu88** [comment]
@fenollp, thank you for the fix! Just curious when is the next release for `[kin-openapi](https://github.com/getkin/kin-openapi)`? Just want to see when I can delete a local forked copy.

**Comment by fenollp** [comment]
here you go https://github.com/getkin/kin-openapi/releases/tag/v0.127.0 ;)
