### ISSUE TITLE
Use of un-exported interface InternalizeRefs 

### ISSUE THREAD

**Issue by valentinegu** [getkin/kin-openapi#994]
Hello Team, 

I have a use-case requiring me to overload the current `RefString\RefPath` functions, 
In my use case the ref may contain non-ascii chars and my overload hashes `Ref` field.
up to `v0.125.0` my use-case was possible since `InternalizeRefs` signature was:
https://github.com/getkin/kin-openapi/blob/43846d5c57b4781018990be6d9349aeee4a9afc1/openapi3/internalize_refs.go#L394
which allowed overloading `refNameResolver` function,

Current implementation: 
https://github.com/getkin/kin-openapi/blob/1a2712f0758d88f28e5ed3a2f4e78975494ff898/openapi3/internalize_refs.go#L493

uses the `componentRef` which isn't exported, as a result my use-case isn't really possible (apart of doing major reimplementation), 
Is there am option to export this interface thus allowing me to achieve previously possible behavior?

**Comment by fenollp** [comment]
Feel free to move https://github.com/getkin/kin-openapi/pull/983 further :)
